(()=>{
 const B='https://www.banknote.ws/COLLECTION/countries/AFR';
 const sets={NAD:{values:[10,20,30,50,100,200],source:'Bank of Namibia',url:'https://www.bon.com.na/Currency/Namibian-notes.aspx',material:'Papel'},BWP:{values:[10,20,50,100,200],source:'Bank of Botswana',url:'https://www.bankofbotswana.bw/notes-and-coins',material:'Papel'}};
 const museum={BWP:{10:['BOT/BOTW0036o.jpg','BOT/BOTW0036r.jpg','BOT/BOTW0036.htm'],20:['BOT/BOT0031o.jpg','BOT/BOT0031r.jpg','BOT/BOT0031.htm'],50:['BOT/BOT0032o.jpg','BOT/BOT0032r.jpg','BOT/BOT0032.htm'],100:['BOT/BOT0033o.jpg','BOT/BOT0033r.jpg','BOT/BOT0033.htm'],200:['BOT/BOT0034o.jpg','BOT/BOT0034r.jpg','BOT/BOT0034.htm']},NAD:{10:['NAM/NAMW0020o.jpg','NAM/NAMW0020r.jpg','NAM/NAMW0020.htm'],20:['NAM/NAMW0021o.jpg','NAM/NAMW0021r.jpg','NAM/NAMW0021.htm'],30:['NAM/NAMW0018o.jpg','NAM/NAMW0018r.jpg','NAM/NAMW0018.htm'],50:['NAM/NAMW0022o.jpg','NAM/NAMW0022r.jpg','NAM/NAMW0022.htm'],100:['NAM/NAMW0023o.jpg','NAM/NAMW0023r.jpg','NAM/NAMW0023.htm'],200:['NAM/NAMW0024o.jpg','NAM/NAMW0024r.jpg','NAM/NAMW0024.htm']}};
 const oldFetch=window.fetch.bind(window);
 window.fetch=async(...args)=>{const req=args[0],url=typeof req==='string'?req:req?.url||'';const r=await oldFetch(...args);
  if(url.includes('/data/countries.json')){const countries=await r.clone().json();const rus=countries.find(c=>c.id==='RUS'||c.currency==='RUB'||c.name==='Rússia');if(rus){rus.continent='Europe';rus.continents=['Europe','Asia'];rus.transcontinental=true}return new Response(JSON.stringify(countries),{status:r.status,statusText:r.statusText,headers:{'Content-Type':'application/json; charset=utf-8'}})}
  if(!url.includes('/data/notes.json'))return r;const notes=await r.clone().json();for(const [currency,c] of Object.entries(sets))for(const value of c.values){let n=notes.find(x=>x.currency===currency&&Number(x.value)===value);if(!n){n={currency,value};notes.push(n)}const m=museum[currency][value];Object.assign(n,{status:'circulating',statusLabel:'Em circulação',source:c.source,material:c.material,front:`${B}/${m[0]}`,back:`${B}/${m[1]}`,imageSource:'Bank Note Museum',imageSourceUrl:`${B}/${m[2]}`,officialUrl:c.url,officialLabel:`Ver ${currency} ${value} na fonte oficial`,imageStatus:'museum-reference'})}return new Response(JSON.stringify(notes),{status:r.status,statusText:r.statusText,headers:{'Content-Type':'application/json; charset=utf-8'}})};
 window.NOTAS_CONTINENT_MATCH=(country,continent)=>Array.isArray(country?.continents)?country.continents.includes(continent):country?.continent===continent;
})();