(()=>{
 const sets={NAD:{values:[10,20,50,100,200],source:'Bank of Namibia',url:'https://www.bon.com.na/Currency/Namibian-notes.aspx',material:'Papel'},BWP:{values:[20,50,100,200],source:'Bank of Botswana',url:'https://www.bankofbotswana.bw/notes-and-coins',material:'Papel'}};
 const pages={BWP:{20:'BOT/BOT0031.htm',50:'BOT/BOT0032.htm',100:'BOT/BOT0033.htm',200:'BOT/BOT0034.htm'},NAD:{10:'NAM/NAMW0020.htm',20:'NAM/NAMW0021.htm',50:'NAM/NAMW0022.htm',100:'NAM/NAMW0023.htm',200:'NAM/NAMW0024.htm'}};
 const countryDefs=[
  {id:'BWA',name:'Botswana',flag:'🇧🇼',continent:'Africa',currency:'BWP',capital:'Gaborone',population:'≈ 2,7 milhões',language:'Inglês / Setswana',history:[['1966–1976','Rand sul-africano e sistema monetário regional'],['1976–hoje','Pula do Botswana (BWP)']]},
  {id:'NAM',name:'Namíbia',flag:'🇳🇦',continent:'Africa',currency:'NAD',capital:'Windhoek',population:'≈ 3 milhões',language:'Inglês',history:[['antes de 1993','Rand sul-africano'],['1993–hoje','Dólar namibiano (NAD), ligado ao rand sul-africano']]}
 ];
 const currencyDefs={
  BWP:{name:'Pula do Botswana',symbol:'P',group:'Botswana',source:'Bank of Botswana',rate:14.7,material:'Papel',notes:[20,50,100,200],countries:['BWA'],focus:false},
  NAD:{name:'Dólar namibiano',symbol:'N$',group:'Namíbia',source:'Bank of Namibia',rate:20.8,material:'Papel',notes:[10,20,50,100,200],countries:['NAM'],focus:false}
 };
 const oldFetch=window.fetch.bind(window);
 window.fetch=async(...args)=>{const req=args[0],url=typeof req==='string'?req:req?.url||'';const r=await oldFetch(...args);
  if(url.includes('/data/countries.json')){const countries=await r.clone().json();const rus=countries.find(c=>c.id==='RUS'||c.currency==='RUB'||c.name==='Rússia');if(rus){rus.continent='Europe';rus.continents=['Europe','Asia'];rus.transcontinental=true}for(const c of countryDefs)if(!countries.some(x=>x.id===c.id))countries.push(c);return new Response(JSON.stringify(countries),{status:r.status,statusText:r.statusText,headers:{'Content-Type':'application/json; charset=utf-8'}})}
  if(url.includes('/data/currencies.json')){const currencies=await r.clone().json();for(const [code,def] of Object.entries(currencyDefs))if(!currencies[code])currencies[code]=def;return new Response(JSON.stringify(currencies),{status:r.status,statusText:r.statusText,headers:{'Content-Type':'application/json; charset=utf-8'}})}
  if(!url.includes('/data/notes.json'))return r;const notes=await r.clone().json();for(const [currency,c] of Object.entries(sets))for(const value of c.values){let n=notes.find(x=>x.currency===currency&&Number(x.value)===value);if(!n){n={currency,value};notes.push(n)}Object.assign(n,{status:'circulating',statusLabel:'Em circulação',source:c.source,material:c.material,front:`/assets/notes/banknotews/${currency.toLowerCase()}/${value}-front.jpg`,back:`/assets/notes/banknotews/${currency.toLowerCase()}/${value}-back.jpg`,imageSource:'Bank Note Museum · cópia local',imageSourceUrl:`https://www.banknote.ws/COLLECTION/countries/AFR/${pages[currency][value]}`,officialUrl:c.url,officialLabel:`Ver ${currency} ${value} na fonte oficial`,imageStatus:'local-reference'})}return new Response(JSON.stringify(notes),{status:r.status,statusText:r.statusText,headers:{'Content-Type':'application/json; charset=utf-8'}})};
 window.NOTAS_CONTINENT_MATCH=(country,continent)=>Array.isArray(country?.continents)?country.continents.includes(continent):country?.continent===continent;
})();