
const CONTINENTS = {
  "Europe": {name:"Europa", center:[18,54], scale:560},
  "Asia": {name:"Ásia", center:[90,37], scale:250},
  "Africa": {name:"África", center:[20,2], scale:350},
  "North America": {name:"América do Norte", center:[-105,45], scale:300},
  "South America": {name:"América do Sul", center:[-62,-18], scale:330},
  "Oceania": {name:"Oceania", center:[145,-25], scale:390}
};
const TOP10=["USD","EUR","GBP","JPY","CNY","CHF","CAD","AUD","SGD","HKD"];
const WORLD_LABELS=[["North America",-105,43],["South America",-62,-20],["Europe",16,51],["Africa",18,1],["Asia",90,33],["Oceania",145,-26]];
let DB={countries:[],currencies:{},notes:[],isoMap:{}}; window.DB=DB; let state={world:null,continent:null,mapMode:"currency"};
let navHistory=[];
let restoringNav=false;
let favorites=new Set(JSON.parse(localStorage.getItem("ndm-favorites")||"[]"));
let compare=[];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], view=$("#view"), crumbs=$("#breadcrumbs");
async function init(){
 [DB.countries,DB.currencies,DB.notes,DB.isoMap]=await Promise.all([
   fetch("/data/countries.json").then(r=>r.json()),
   fetch("/data/currencies.json").then(r=>r.json()),
   fetch("/data/notes.json").then(r=>r.json()),
   fetch("/data/iso-map.json").then(r=>r.json())
 ]);
 bindChrome();showHome();refreshRates();
 if("serviceWorker" in navigator)navigator.serviceWorker.register("/service-worker.js").catch(()=>{});
}
function bindChrome(){
 window.addEventListener("popstate",()=>{ if(navHistory.length)goBack(); });
 $("#menuBtn").onclick=()=>$("#sidebar").classList.toggle("open");
 $$("[data-nav]").forEach(el=>el.onclick=()=>navigate(el.dataset.nav));
 $("#searchInput").addEventListener("input",search);
 document.addEventListener("click",e=>{if(e.target.matches("[data-close-modal]"))closeModal();if(e.target.matches("[data-close-viewer]"))closeImageViewer();if(!e.target.closest(".search-wrap"))$("#searchResults").classList.remove("show")});
 document.addEventListener("keydown",e=>{if(e.key==="Escape"){if(!$("#imageViewer").classList.contains("hidden"))closeImageViewer();else if(!$("#noteModal").classList.contains("hidden"))closeModal();}});
}

function currentLocation(){
  return {
    kind: state.currentKind || "home",
    id: state.currentId || null,
    continent: state.continent || null
  };
}
function rememberLocation(){
  if(restoringNav)return;
  const loc=currentLocation();
  const last=navHistory[navHistory.length-1];
  if(!last || JSON.stringify(last)!==JSON.stringify(loc)) navHistory.push(loc);
  if(navHistory.length>30)navHistory.shift();
}
function goBack(){
  const prev=navHistory.pop();
  if(!prev){showHome(true);return}
  restoringNav=true;
  if(prev.kind==="continent")showContinent(prev.id,true);
  else if(prev.kind==="country")showCountry(prev.id,true);
  else if(prev.kind==="currency")showCurrency(prev.id,true);
  else if(prev.kind==="countries")showCountries(true);
  else if(prev.kind==="notes")showAllNotes(true);
  else if(prev.kind==="exchange")showExchange(true);
  else if(prev.kind==="favorites")showFavorites(true);
  else showHome(true);
  restoringNav=false;
}
function backButton(label="Voltar"){
  return `<button class="ghost-btn app-back" data-app-back>← ${label}</button>`;
}
function bindBack(){
  $$("[data-app-back]").forEach(b=>b.onclick=goBack);
}
function setActive(name){$$(".nav-item").forEach(x=>x.classList.toggle("active",x.dataset.nav===name))}
function navigate(name){$("#sidebar").classList.remove("open");setActive(name);({home:showHome,countries:showCountries,notes:showAllNotes,exchange:showExchange,favorites:showFavorites,about:showAbout}[name]||showHome)()}
function key(code,val){return `${code}:${val}`}
function saveFav(){localStorage.setItem("ndm-favorites",JSON.stringify([...favorites]))}
function toggleFav(code,val,rerender=false){const k=key(code,val);favorites.has(k)?favorites.delete(k):favorites.add(k);saveFav();if(rerender)showFavorites();else{bindNoteCards();$$(`[data-fav="${k}"]`).forEach(b=>{b.classList.toggle("on",favorites.has(k));b.textContent=favorites.has(k)?"♥":"♡"})}}
function toggleCompare(code,val){
 const k=key(code,val),i=compare.indexOf(k);if(i>=0)compare.splice(i,1);else if(compare.length<3)compare.push(k);else return alert("Pode comparar até 3 notas.");
 updateCompareBar();$$(`[data-compare="${k}"]`).forEach(b=>b.classList.toggle("on",compare.includes(k)));
}
function updateCompareBar(){
 compareBar.classList.toggle("hidden",!compare.length);compareBar.innerHTML=compare.length?`<span>${compare.length} nota(s) selecionada(s)</span><div><button class="ghost-btn" id="clearCompare">Limpar</button><button class="primary-btn" id="doCompare" ${compare.length<2?"disabled":""}>Comparar</button></div>`:"";if(compare.length){$("#clearCompare").onclick=()=>{compare=[];updateCompareBar();bindNoteCards()};$("#doCompare").onclick=showComparison}
}
function hero(title,sub,extra=""){return `<div class="hero"><div><span class="eyebrow">ATLAS MONETÁRIO</span><h1>${title}</h1><p>${sub}</p></div>${extra}</div>`}
function showHome(fromBack=false){
 if(!fromBack)rememberLocation();state.currentKind="home";state.currentId=null;state.continent=null;
 crumbs.textContent="Mundo";setActive("home");
 const top=TOP10.map(currencyCard).join("");
 view.innerHTML=hero("Explore as notas do mundo","Navegue pelo mapa, entre num continente, descubra a moeda de cada país e abra cada nota em frente e verso.",`<button class="primary-btn" id="randomBtn">Descobrir uma nota</button>`)+`<div class="map-card"><svg id="worldMap"></svg><div class="map-toolbar"><button id="zoomIn">+</button><button id="zoomOut">−</button><button id="resetMap">⌂</button></div><div class="map-hint">Toque num continente para explorar</div></div><div class="section-head"><div><h2>Top 10 moedas globais</h2><p>Seleção editorial de moedas com forte papel internacional, reserva, comércio ou relevância regional.</p></div></div><div class="currency-band">${top}</div><div class="section-head"><div><h2>Continentes</h2><p>Atalho para explorar países e áreas monetárias.</p></div></div><div class="continent-grid">${Object.entries(CONTINENTS).map(([k,v])=>`<button data-continent="${k}"><strong>${v.name}</strong><span>Explorar →</span></button>`).join("")}</div>`;
 $("#randomBtn").onclick=randomNote;$$('[data-continent]').forEach(b=>b.onclick=()=>showContinent(b.dataset.continent));$$('[data-currency]').forEach(b=>b.onclick=()=>showCurrency(b.dataset.currency));renderWorldMap();
}
async function loadWorld(){if(state.world)return state.world;state.world=await fetch("https://cdn.jsdelivr.net/npm/world-atlas@2/countries-110m.json").then(r=>r.json());return state.world}
async function renderWorldMap(continent=null){
 const data=await loadWorld(),svg=d3.select("#worldMap"),node=svg.node(),w=node.clientWidth||900,h=node.clientHeight||500;svg.attr("viewBox",`0 0 ${w} ${h}`);svg.selectAll("*").remove();
 const projection=d3.geoNaturalEarth1(),cfg=continent?CONTINENTS[continent]:null;projection.translate([w/2,h/2]).scale(cfg?cfg.scale*(w/1000):Math.min(w/6.1,h/3.2));if(cfg)projection.center(cfg.center);
 const path=d3.geoPath(projection),countries=topojson.feature(data,data.objects.countries).features,g=svg.append("g");
 const colors=["#163247","#183c38","#40311e","#352742","#3d2430","#26334a"];
 g.selectAll("path").data(countries).join("path").attr("d",path).attr("class","country-path").attr("fill",d=>{const iso=DB.isoMap[String(d.id).padStart(3,"0")],c=DB.countries.find(x=>x.id===iso);if(!c)return "#101b24";let ci=Object.keys(CONTINENTS).indexOf(c.continent);return colors[Math.max(0,ci)]}).on("click",(_,d)=>{const iso=DB.isoMap[String(d.id).padStart(3,"0")],c=DB.countries.find(x=>x.id===iso);if(c){continent?(state.mapMode==="country"?showCountry(c.id):showCurrency(c.currency)):showContinent(c.continent)}});
 if(!continent){const labels=g.selectAll("g.cont-label").data(WORLD_LABELS).join("g").attr("class","cont-label").attr("transform",d=>{const p=projection([d[1],d[2]]);return `translate(${p[0]},${p[1]})`}).style("cursor","pointer").on("click",(_,d)=>showContinent(d[0]));labels.append("rect").attr("x",-72).attr("y",-17).attr("width",144).attr("height",34).attr("rx",17);labels.append("text").attr("text-anchor","middle").attr("dy","5").text(d=>CONTINENTS[d[0]].name)}
 let z=1;$("#zoomIn").onclick=()=>{z=Math.min(4,z*1.25);g.attr("transform",`translate(${w*(1-z)/2},${h*(1-z)/2}) scale(${z})`)};$("#zoomOut").onclick=()=>{z=Math.max(.7,z/1.25);g.attr("transform",`translate(${w*(1-z)/2},${h*(1-z)/2}) scale(${z})`)};$("#resetMap").onclick=()=>continent?showContinent(continent):showHome();
}
function currencyCard(code){const c=DB.currencies[code],ct=DB.countries.filter(x=>x.currency===code);return `<div class="card currency-card" data-currency="${code}"><div class="card-topline"><span class="big-symbol">${c.symbol}</span><span class="mini-badge">${code}</span></div><h3>${c.group}</h3><p>${c.name}</p><small>${ct.length} país(es) · ${c.notes.length} denominações</small></div>`}
function countryCard(c){return `<div class="card" data-country="${c.id}"><div class="card-topline"><span class="flag">${c.flag}</span><span class="mini-badge">${c.currency}</span></div><h3>${c.name}</h3><p>${DB.currencies[c.currency].name}</p></div>`}
function showContinent(k,fromBack=false){
 if(!fromBack)rememberLocation();state.currentKind="continent";state.currentId=k;state.continent=k;crumbs.textContent=`Mundo › ${CONTINENTS[k].name}`;setActive("home");
 const cs=DB.countries.filter(c=>c.continent===k),codes=[...new Set(cs.map(c=>c.currency))];
 view.innerHTML=`<div class="section-head"><div><h2>${CONTINENTS[k].name}</h2><p>${cs.length} países · ${codes.length} áreas monetárias nesta versão.</p></div><button class="ghost-btn" id="backWorld">← Mundo</button></div><div class="section-head" style="margin-top:4px"><div><h3 style="margin:0">Como quer ver o mapa?</h3><p>Países abre a ficha nacional; Moedas agrupa os países que partilham a mesma moeda.</p></div><div class="map-mode-switch"><button id="modeCountries" class="${state.mapMode==="country"?"active":""}">Países</button><button id="modeCurrencies" class="${state.mapMode==="currency"?"active":""}">Moedas</button></div></div><div class="map-card" style="height:46vh;min-height:350px"><svg id="worldMap"></svg><div class="map-toolbar"><button id="zoomIn">+</button><button id="zoomOut">−</button><button id="resetMap">⌂</button></div><div class="map-hint">${state.mapMode==="currency"?"Mesma cor = mesma moeda · toque num país para abrir a moeda":"Toque num país para abrir a ficha do país"}</div></div><div class="map-legend">${codes.map((code,i)=>{const c=DB.currencies[code];return `<span class="legend-chip" data-currency="${code}"><span class="legend-dot" style="background:${["#53a6d8","#d58d52","#71b98e","#b379c2","#d2b34f","#7c8ee3","#dd6f79","#54b6b0","#a58d61","#c678a8","#6d9bc4"][i%11]}"></span>${code} · ${c.name}</span>`}).join("")}</div><div class="section-head"><div><h2>Áreas monetárias</h2><p>Os países que usam a mesma moeda são tratados como um grupo.</p></div></div><div class="currency-band">${codes.map(currencyCard).join("")}</div><div class="section-head"><div><h2>Países</h2><p>Lista individual — útil para entrar na história monetária de cada país.</p></div></div><div class="grid">${cs.map(countryCard).join("")}</div>`;
 $("#backWorld").onclick=goBack;$("#modeCountries").onclick=()=>{state.mapMode="country";showContinent(k)};$("#modeCurrencies").onclick=()=>{state.mapMode="currency";showContinent(k)};$$('[data-currency]').forEach(x=>x.onclick=()=>showCurrency(x.dataset.currency));$$('[data-country]').forEach(x=>x.onclick=()=>showCountry(x.dataset.country));renderWorldMap(k);
}
function showCountries(fromBack=false){if(!fromBack)rememberLocation();state.currentKind="countries";state.currentId=null;crumbs.textContent="Países";setActive("countries");view.innerHTML=hero("Países","Selecione um país para abrir a ficha monetária.")+`<div class="filter-panel"><input id="countryFilter" placeholder="Filtrar países…"><select id="continentFilter"><option value="">Todos os continentes</option>${Object.entries(CONTINENTS).map(([k,v])=>`<option value="${k}">${v.name}</option>`).join("")}</select><select id="currencyFilter"><option value="">Todas as moedas</option>${Object.keys(DB.currencies).map(c=>`<option>${c}</option>`).join("")}</select></div><div id="countryGrid"></div>`;const render=()=>{const q=$("#countryFilter").value.toLowerCase(),co=$("#continentFilter").value,cu=$("#currencyFilter").value,items=DB.countries.filter(c=>(!q||c.name.toLowerCase().includes(q))&&(!co||c.continent===co)&&(!cu||c.currency===cu));$("#countryGrid").innerHTML=`<div class="grid">${items.map(countryCard).join("")}</div>`;$$('[data-country]').forEach(x=>x.onclick=()=>showCountry(x.dataset.country))};["countryFilter","continentFilter","currencyFilter"].forEach(id=>$("#"+id).addEventListener("input",render));render()}
function showCountry(id,fromBack=false){if(!fromBack)rememberLocation();state.currentKind="country";state.currentId=id;const c=DB.countries.find(x=>x.id===id),cur=DB.currencies[c.currency];crumbs.textContent=`${CONTINENTS[c.continent].name} › ${c.name}`;view.innerHTML=`<div class="section-head" style="margin-top:4px"><div>${backButton(state.continent?CONTINENTS[state.continent].name:"Voltar")}</div></div><div class="panel country-currency-hero"><div><div class="country-title"><span class="flag">${c.flag}</span><div><h1>${c.name}</h1><p>${cur.name} · ${c.currency} · ${cur.symbol}</p></div></div><p class="history-intro">A ficha do país contextualiza a moeda atual e mostra a evolução monetária antes de entrar nas notas em circulação.</p></div><div class="huge-currency">${cur.symbol}</div></div><div class="detail-layout" style="margin-top:18px"><div class="panel"><h3>Breve história da moeda</h3><div class="timeline">${c.history.map(h=>`<div class="timeline-item"><strong>${h[0]}</strong><span>${h[1]}</span></div>`).join("")}</div></div><aside class="panel"><h3>Ficha rápida</h3><div class="info-row"><span>Capital</span><strong>${c.capital}</strong></div><div class="info-row"><span>População</span><strong>${c.population}</strong></div><div class="info-row"><span>Idioma</span><strong>${c.language}</strong></div><div class="info-row"><span>Moeda</span><strong>${c.currency}</strong></div><div class="info-row"><span>Emissor</span><strong>${cur.source}</strong></div><div class="info-row"><span>1 EUR ≈</span><strong>${cur.rate} ${c.currency}</strong></div><button class="primary-btn" id="openCurrency" style="width:100%;margin-top:14px">Abrir ${cur.name}</button></aside></div><div class="section-head"><div><h2>Notas associadas</h2><p>Uma entrada por valor; não separamos séries na grelha principal.</p></div></div>${notesGrid(c.currency)}`;bindBack();$("#openCurrency").onclick=()=>showCurrency(c.currency);bindNoteCards()}
function showCurrency(code,fromBack=false){if(!fromBack)rememberLocation();state.currentKind="currency";state.currentId=code;const c=DB.currencies[code],members=DB.countries.filter(x=>x.currency===code);crumbs.textContent=`Moedas › ${c.name}`;view.innerHTML=`<div class="section-head" style="margin-top:4px"><div>${backButton(state.continent?CONTINENTS[state.continent].name:"Voltar")}</div></div><div class="panel country-currency-hero"><div><span class="mini-badge">${code}</span><h1>${c.name}</h1><p>${c.group} · ${c.source}</p><p class="history-intro">Página da área monetária. Quando uma moeda é partilhada, todos os países aparecem juntos antes das notas.</p></div><div class="huge-currency">${c.symbol}</div></div><div class="dashboard-strip"><div class="metric"><strong>${c.notes.length}</strong><small>denominações</small></div><div class="metric"><strong>${members.length}</strong><small>países nesta base</small></div><div class="metric"><strong>${c.material}</strong><small>suporte principal</small></div><div class="metric"><strong>${c.rate}</strong><small>${code} por 1 EUR*</small></div></div>${c.editorial?`<div class="detail-layout"><div class="panel"><span class="mini-badge">MOEDA GLOBAL #${c.focusRank}</span><h3>${c.editorial.role}</h3><p class="history-intro">${c.editorial.fact}</p></div><aside class="panel"><h3>Emissão e segurança</h3><div class="info-row"><span>Emissor</span><strong>${c.editorial.issuer}</strong></div><p class="history-intro">${c.editorial.security}</p></aside></div>`:""}<div class="section-head"><div><h2>Países / área monetária</h2></div></div><div class="grid">${members.map(countryCard).join("")}</div><div class="section-head"><div><h2>Notas</h2><p>Clique para ver frente, verso e ficha detalhada.</p></div></div>${notesGrid(code)}<p class="source-note">* Câmbio indicativo; a app tenta atualizar via serviço externo e mantém fallback local para demonstração.</p>`;bindBack();$$('[data-country]').forEach(x=>x.onclick=()=>showCountry(x.dataset.country));bindNoteCards()}
function notesGrid(code){return `<div class="note-grid">${DB.notes.filter(n=>n.currency===code).map(noteCard).join("")}</div>`}
function noteCard(n){const c=DB.currencies[n.currency],k=key(n.currency,n.value),legacy=n.status!=="circulating";return `<article class="note-card" data-note="${k}"><button class="compare-btn ${compare.includes(k)?"on":""}" data-compare="${k}" title="Comparar">≍</button><button class="fav-btn ${favorites.has(k)?"on":""}" data-fav="${k}" title="Favorito">${favorites.has(k)?"♥":"♡"}</button><div class="note-visual"><img loading="lazy" src="${n.front}" alt="${n.value} ${c.name}"></div><div class="note-meta"><strong>${c.symbol}${n.value}</strong><small>${c.name} · ${n.currency}</small><div class="status-line"><span class="status-dot ${legacy?"legacy":""}"></span>${n.statusLabel}</div></div></article>`}
function bindNoteCards(){$$('[data-note]').forEach(card=>card.onclick=e=>{if(e.target.closest("button"))return;let [c,v]=card.dataset.note.split(":");openNote(c,+v)});$$('[data-fav]').forEach(b=>b.onclick=e=>{e.stopPropagation();let [c,v]=b.dataset.fav.split(":");toggleFav(c,+v)});$$('[data-compare]').forEach(b=>b.onclick=e=>{e.stopPropagation();let [c,v]=b.dataset.compare.split(":");toggleCompare(c,+v)})}
function openNote(code,value){const n=DB.notes.find(x=>x.currency===code&&x.value===value),c=DB.currencies[code],k=key(code,value),countries=DB.countries.filter(x=>x.currency===code);const sourceLine=n.imageStatus==="official" ? `<div class="notice" style="margin-top:16px"><strong>Imagem oficial.</strong> Fonte: ${n.imageSource||n.source}.${code==="EUR"?" A marca SPECIMEN é exigida pelo BCE para reproduções digitais integrais.":""}</div>` : `<div class="notice" style="margin-top:16px"><strong>Imagem demonstrativa.</strong> Esta denominação ainda aguarda substituição por um asset oficial/licenciado.</div>`;$("#modalBody").innerHTML=`<div class="note-detail-head"><div><span class="mini-badge">${code}</span><h2>${c.symbol}${value} · ${c.name}</h2></div><div class="note-detail-actions"><button class="ghost-btn" id="modalFav">${favorites.has(k)?"♥ Favorita":"♡ Favorito"}</button><button class="ghost-btn" id="modalCompare">≍ Comparar</button></div></div><div class="modal-note-grid"><div class="modal-note-side"><h4>Frente</h4><button class="note-image-button" data-full-image="${n.front}" data-full-label="${c.symbol}${value} · Frente"><img src="${n.front}" alt="Frente"></button><small class="tap-hint">Toque na imagem para ampliar</small></div><div class="modal-note-side"><h4>Verso</h4><button class="note-image-button" data-full-image="${n.back}" data-full-label="${c.symbol}${value} · Verso"><img src="${n.back}" alt="Verso"></button><small class="tap-hint">Toque na imagem para ampliar</small></div></div><div class="modal-facts"><div class="stat"><small>Valor</small><strong>${c.symbol}${value}</strong></div><div class="stat"><small>Estado</small><strong>${n.statusLabel}</strong></div><div class="stat"><small>Material</small><strong>${n.material}</strong></div><div class="stat"><small>Emissor</small><strong>${n.source}</strong></div><div class="stat"><small>País(es)</small><strong>${countries.map(x=>x.flag).join(" ")}</strong></div><div class="stat"><small>Equivalência EUR*</small><strong>≈ €${(value/c.rate).toLocaleString("pt-PT",{maximumFractionDigits:2})}</strong></div>${n.dimensions?`<div class="stat"><small>Dimensões</small><strong>${n.dimensions}</strong></div>`:""}</div>${sourceLine}`;$("#modalFav").onclick=()=>{toggleFav(code,value);openNote(code,value)};$("#modalCompare").onclick=()=>{toggleCompare(code,value);closeModal()};$$('[data-full-image]').forEach(btn=>btn.onclick=()=>openImageViewer(btn.dataset.fullImage,btn.dataset.fullLabel));$("#noteModal").classList.remove("hidden");$("#noteModal").setAttribute("aria-hidden","false")}
function openImageViewer(src,label="Nota"){const viewer=$("#imageViewer"),img=$("#imageViewerImg"),title=$("#imageViewerTitle");img.src=src;img.alt=label;title.textContent=label;viewer.classList.remove("hidden");viewer.setAttribute("aria-hidden","false");document.body.classList.add("viewer-open")}
function closeImageViewer(){const viewer=$("#imageViewer");const active=document.activeElement;if(active&&viewer.contains(active))active.blur();viewer.classList.add("hidden");viewer.setAttribute("aria-hidden","true");$("#imageViewerImg").src="";document.body.classList.remove("viewer-open")}
function closeModal(){const modal=$("#noteModal");const active=document.activeElement;if(active&&modal.contains(active))active.blur();modal.classList.add("hidden");modal.setAttribute("aria-hidden","true")}
function showComparison(){if(compare.length<2)return alert("Escolha pelo menos duas notas.");const arr=compare.map(k=>{let [c,v]=k.split(":");return DB.notes.find(n=>n.currency===c&&n.value==+v)}),cols=arr.length;$("#modalBody").innerHTML=`<h2>Comparar notas</h2><p style="color:var(--muted)">Comparação visual e monetária de ${cols} denominações.</p><div class="compare-table" style="--cols:${cols}"><div class="compare-cell"></div>${arr.map(n=>`<div class="compare-cell"><img src="${n.front}"></div>`).join("")}<div class="compare-cell"><strong>Nota</strong></div>${arr.map(n=>`<div class="compare-cell"><strong>${DB.currencies[n.currency].symbol}${n.value}</strong><br><small>${n.currency}</small></div>`).join("")}<div class="compare-cell"><strong>Moeda</strong></div>${arr.map(n=>`<div class="compare-cell">${DB.currencies[n.currency].name}</div>`).join("")}<div class="compare-cell"><strong>Em EUR*</strong></div>${arr.map(n=>`<div class="compare-cell">€${(n.value/DB.currencies[n.currency].rate).toLocaleString("pt-PT",{maximumFractionDigits:2})}</div>`).join("")}<div class="compare-cell"><strong>Material</strong></div>${arr.map(n=>`<div class="compare-cell">${n.material}</div>`).join("")}</div><p class="source-note">* Equivalência apenas indicativa.</p>`;$("#noteModal").classList.remove("hidden")}
function search(){const q=$("#searchInput").value.trim().toLowerCase(),box=$("#searchResults");if(!q){box.classList.remove("show");return}const cs=DB.countries.filter(c=>c.name.toLowerCase().includes(q)||c.currency.toLowerCase().includes(q)).slice(0,6),ms=Object.entries(DB.currencies).filter(([k,v])=>k.toLowerCase().includes(q)||v.name.toLowerCase().includes(q)).slice(0,5);box.innerHTML=[...cs.map(c=>`<button data-s-country="${c.id}"><span>${c.flag}</span><div><strong>${c.name}</strong><small>${c.currency}</small></div></button>`),...ms.map(([k,v])=>`<button data-s-currency="${k}"><span>${v.symbol}</span><div><strong>${v.name}</strong><small>${k}</small></div></button>`)].join("");box.classList.add("show");$$('[data-s-country]').forEach(b=>b.onclick=()=>{box.classList.remove("show");showCountry(b.dataset.sCountry)});$$('[data-s-currency]').forEach(b=>b.onclick=()=>{box.classList.remove("show");showCurrency(b.dataset.sCurrency)})}
function showAllNotes(fromBack=false){if(!fromBack)rememberLocation();state.currentKind="notes";state.currentId=null;crumbs.textContent="Notas";setActive("notes");view.innerHTML=hero("Todas as notas","Filtre e compare denominações de diferentes moedas.",`<button class="primary-btn" id="randomNote">Nota aleatória</button>`)+`<div class="filter-panel"><input id="noteSearch" placeholder="Valor ou moeda…"><select id="noteCont"><option value="">Todos os continentes</option>${Object.entries(CONTINENTS).map(([k,v])=>`<option value="${k}">${v.name}</option>`).join("")}</select><select id="noteCur"><option value="">Todas as moedas</option>${Object.keys(DB.currencies).map(c=>`<option value="${c}">${c} · ${DB.currencies[c].name}</option>`).join("")}</select></div><div id="allNotes"></div>`;$("#randomNote").onclick=randomNote;const render=()=>{const q=$("#noteSearch").value.toLowerCase(),cont=$("#noteCont").value,cur=$("#noteCur").value;let ns=DB.notes.filter(n=>{let c=DB.currencies[n.currency],countries=DB.countries.filter(x=>x.currency===n.currency);return (!q||`${n.value} ${n.currency} ${c.name}`.toLowerCase().includes(q))&&(!cur||n.currency===cur)&&(!cont||countries.some(x=>x.continent===cont))});$("#allNotes").innerHTML=`<div class="note-grid">${ns.map(noteCard).join("")}</div>`;bindNoteCards()};["noteSearch","noteCont","noteCur"].forEach(id=>$("#"+id).addEventListener("input",render));render()}
function randomNote(){const n=DB.notes[Math.floor(Math.random()*DB.notes.length)],c=DB.currencies[n.currency];view.innerHTML=hero("Descoberta aleatória","Uma forma de explorar o atlas sem escolher país ou moeda.")+`<div class="panel random-card"><div class="note-visual"><img src="${n.front}"></div><div><span class="mini-badge">${n.currency}</span><h2>${c.symbol}${n.value} · ${c.name}</h2><p>${n.statusLabel} · ${n.material}</p><div class="action-row" style="justify-content:flex-start"><button class="primary-btn" id="openRnd">Ver frente e verso</button><button class="ghost-btn" id="anotherRnd">Outra nota</button></div></div></div>`;$("#openRnd").onclick=()=>openNote(n.currency,n.value);$("#anotherRnd").onclick=randomNote}
function showFavorites(fromBack=false){if(!fromBack)rememberLocation();state.currentKind="favorites";state.currentId=null;crumbs.textContent="Favoritos";setActive("favorites");let ns=DB.notes.filter(n=>favorites.has(key(n.currency,n.value)));view.innerHTML=hero("Favoritos",favorites.size?`${favorites.size} notas guardadas neste dispositivo.`:"Ainda não guardou nenhuma nota.")+(ns.length?`<div class="note-grid">${ns.map(noteCard).join("")}</div>`:`<div class="panel empty">Toque no ♡ de qualquer nota para a guardar aqui. Os favoritos persistem no navegador.</div>`);bindNoteCards()}
async function refreshRates(){try{const r=await fetch("https://api.frankfurter.app/latest?from=EUR"),j=await r.json();Object.entries(j.rates||{}).forEach(([code,val])=>{if(DB.currencies[code])DB.currencies[code].rate=val})}catch(e){}}
function showExchange(fromBack=false){if(!fromBack)rememberLocation();state.currentKind="exchange";state.currentId=null;crumbs.textContent="Câmbio";setActive("exchange");view.innerHTML=hero("Conversor","Conversão rápida entre moedas da base. A app tenta obter taxas atuais e usa fallback se necessário.")+`<div class="panel" style="max-width:800px;margin:auto"><div class="exchange-box"><div><input id="amt" type="number" value="100" min="0"><select id="from">${currencyOptions("EUR")}</select></div><strong>→</strong><div><select id="to">${currencyOptions("USD")}</select><div class="exchange-value" id="conv"></div></div></div><div class="notice" style="margin-top:18px">O câmbio é informativo e não substitui uma cotação bancária/comercial.</div></div>`;["amt","from","to"].forEach(id=>$("#"+id).addEventListener("input",convert));convert()}
function currencyOptions(sel){return Object.entries(DB.currencies).map(([k,v])=>`<option ${k===sel?"selected":""} value="${k}">${k} · ${v.name}</option>`).join("")}
function convert(){let amount=+$("#amt").value||0,from=$("#from").value,to=$("#to").value,eur=amount/DB.currencies[from].rate,result=eur*DB.currencies[to].rate;$("#conv").textContent=`${DB.currencies[to].symbol}${result.toLocaleString("pt-PT",{maximumFractionDigits:2})}`}
function showAbout(){crumbs.textContent="Sobre";setActive("about");view.innerHTML=hero("Notas do Mundo","Atlas visual e geográfico de moedas e notas.")+`<div class="detail-layout"><div class="panel"><h3>O que esta versão permite validar</h3><p class="history-intro">Mapa → continente → área monetária → país → história → notas → frente/verso. Também existem pesquisa, favoritos persistentes, comparação, nota aleatória e conversor.</p><h3>Princípio editorial</h3><p class="history-intro">A grelha mostra uma entrada por denominação. Séries ou variantes só são mencionadas quando necessárias para explicar o visual ou o estatuto da nota.</p></div></div>`}
init();