(() => {
  const placeholder=(code,value)=>'data:image/svg+xml;charset=UTF-8,'+encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 720 320"><rect width="720" height="320" rx="18" fill="#0c1824"/><rect x="18" y="18" width="684" height="284" rx="14" fill="none" stroke="#526170" stroke-width="2"/><text x="360" y="118" text-anchor="middle" fill="#d7e2ea" font-family="Arial,sans-serif" font-size="42" font-weight="700">${code} ${value}</text><text x="360" y="175" text-anchor="middle" fill="#90a1ae" font-family="Arial,sans-serif" font-size="24">IMAGEM EM PREPARAÇÃO</text><text x="360" y="216" text-anchor="middle" fill="#6f8392" font-family="Arial,sans-serif" font-size="18">VER FONTE OFICIAL</text></svg>`);
  const countries=[
    {id:'IDN',name:'Indonésia',flag:'🇮🇩',continent:'Asia',currency:'IDR',capital:'Jacarta',population:'≈ 285 milhões',language:'Indonésio',history:[['1946–hoje','Rupia indonésia (IDR)']]},
    {id:'MYS',name:'Malásia',flag:'🇲🇾',continent:'Asia',currency:'MYR',capital:'Kuala Lumpur',population:'≈ 35 milhões',language:'Malaio',history:[['1967–hoje','Ringgit malaio (MYR)']]},
    {id:'THA',name:'Tailândia',flag:'🇹🇭',continent:'Asia',currency:'THB',capital:'Banguecoque',population:'≈ 71 milhões',language:'Tailandês',history:[['1902–hoje','Baht tailandês (THB)']]},
    {id:'PHL',name:'Filipinas',flag:'🇵🇭',continent:'Asia',currency:'PHP',capital:'Manila',population:'≈ 116 milhões',language:'Filipino / Inglês',history:[['1949–hoje','Peso filipino emitido pelo Bangko Sentral e antecessores']]},
    {id:'VNM',name:'Vietname',flag:'🇻🇳',continent:'Asia',currency:'VND',capital:'Hanói',population:'≈ 101 milhões',language:'Vietnamita',history:[['1978–hoje','Đồng vietnamita unificado (VND)']]}
  ];
  const cfg={
    IDR:{name:'Rupia indonésia',symbol:'Rp',group:'Indonésia',source:'Bank Indonesia',material:'Papel',notes:[1000,2000,5000,10000,20000,50000,100000],countries:['IDN'],officialUrl:'https://www.bi.go.id/en/rupiah/gambar-uang/Default.aspx',series:'Emissão 2022'},
    MYR:{name:'Ringgit malaio',symbol:'RM',group:'Malásia',source:'Bank Negara Malaysia',material:'Papel / polímero',notes:[1,5,10,20,50,100],countries:['MYS'],officialUrl:'https://www.bnm.gov.my/currency/banknotes',series:'4.ª série · 2012–presente'},
    THB:{name:'Baht tailandês',symbol:'฿',group:'Tailândia',source:'Bank of Thailand',material:'Papel / polímero',notes:[20,50,100,500,1000],countries:['THA'],officialUrl:'https://www.bot.or.th/en/our-roles/banknotes/History-and-Series-of-Banknote-And-Commemorative/current-series-of-banknotes.html',series:'Série 17 · atual'},
    PHP:{name:'Peso filipino',symbol:'₱',group:'Filipinas',source:'Bangko Sentral ng Pilipinas',material:'Papel / polímero conforme emissão',notes:[20,50,100,200,500,1000],countries:['PHL'],officialUrl:'https://www.bsp.gov.ph/Pages/CoinsAndNotes/CoinsAndNotes.aspx',series:'New Generation Currency / polímero'},
    VND:{name:'Đồng vietnamita',symbol:'₫',group:'Vietname',source:'State Bank of Vietnam',material:'Papel / polímero',notes:[1000,2000,5000,10000,20000,50000,100000,200000,500000],countries:['VNM'],officialUrl:'https://www.sbv.gov.vn/',series:'Série atual'}
  };
  const previousFetch=window.fetch.bind(window);
  window.fetch=async(...args)=>{const req=args[0],url=typeof req==='string'?req:req?.url||'';const response=await previousFetch(...args);
    if(url.includes('/data/countries.json')){const data=await response.clone().json();for(const c of countries){const old=data.find(x=>x.id===c.id);old?Object.assign(old,c):data.push(c)}return new Response(JSON.stringify(data),{status:response.status,statusText:response.statusText,headers:{'Content-Type':'application/json; charset=utf-8'}})}
    if(url.includes('/data/currencies.json')){const data=await response.clone().json();for(const [code,c] of Object.entries(cfg)){data[code]=Object.assign(data[code]||{},{name:c.name,symbol:c.symbol,group:c.group,source:c.source,rate:0,material:c.material,notes:c.notes,countries:c.countries,focus:false})}return new Response(JSON.stringify(data),{status:response.status,statusText:response.statusText,headers:{'Content-Type':'application/json; charset=utf-8'}})}
    if(url.includes('/data/notes.json')){const data=await response.clone().json();for(const [code,c] of Object.entries(cfg))for(const value of c.notes){let n=data.find(x=>x.currency===code&&Number(x.value)===value);if(!n){n={currency:code,value};data.push(n)}Object.assign(n,{front:placeholder(code,value),back:placeholder(code,value),status:'circulating',statusLabel:'Em circulação',source:c.source,material:c.material,series:c.series,imageStatus:'official-link',imageSource:c.source,imageSourceUrl:c.officialUrl,officialUrl:c.officialUrl,officialLabel:`Ver ${code} ${value} na fonte oficial`})}return new Response(JSON.stringify(data),{status:response.status,statusText:response.statusText,headers:{'Content-Type':'application/json; charset=utf-8'}})}
    return response;
  };
})();