(() => {
  const O={
    "HUF:500":{front:"/assets/notes/banknotews/huf/500-front.jpg",back:"/assets/notes/banknotews/huf/500-back.jpg",imageStatus:'local-reference',imageSource:'Banknote Museum · banknote.ws',imageSourceUrl:"https://www.banknote.ws/COLLECTION/countries/EUR/HUN/HUNW2018-00500.htm"},
    "HUF:1000":{front:"/assets/notes/banknotews/huf/1000-front.jpg",back:"/assets/notes/banknotews/huf/1000-back.jpg",imageStatus:'local-reference',imageSource:'Banknote Museum · banknote.ws',imageSourceUrl:"https://www.banknote.ws/COLLECTION/countries/EUR/HUN/HUN0203.htm"},
    "HUF:2000":{front:"/assets/notes/banknotews/huf/2000-front.jpg",back:"/assets/notes/banknotews/huf/2000-back.jpg",imageStatus:'local-reference',imageSource:'Banknote Museum · banknote.ws',imageSourceUrl:"https://www.banknote.ws/COLLECTION/countries/EUR/HUN/HUN0204.htm"},
    "HUF:5000":{front:"/assets/notes/banknotews/huf/5000-front.jpg",back:"/assets/notes/banknotews/huf/5000-back.jpg",imageStatus:'local-reference',imageSource:'Banknote Museum · banknote.ws',imageSourceUrl:"https://www.banknote.ws/COLLECTION/countries/EUR/HUN/HUN0205.htm"},
    "HUF:10000":{front:"/assets/notes/banknotews/huf/10000-front.jpg",back:"/assets/notes/banknotews/huf/10000-back.jpg",imageStatus:'local-reference',imageSource:'Banknote Museum · banknote.ws',imageSourceUrl:"https://www.banknote.ws/COLLECTION/countries/EUR/HUN/HUN0206.htm"},
    "HUF:20000":{front:"/assets/notes/banknotews/huf/20000-front.jpg",back:"/assets/notes/banknotews/huf/20000-back.jpg",imageStatus:'local-reference',imageSource:'Banknote Museum · banknote.ws',imageSourceUrl:"https://www.banknote.ws/COLLECTION/countries/EUR/HUN/HUN0207.htm"},
    "RSD:10":{front:"/assets/notes/banknotews/rsd/10-front.jpg",back:"/assets/notes/banknotews/rsd/10-back.jpg",imageStatus:'local-reference',imageSource:'Banknote Museum · banknote.ws',imageSourceUrl:"https://www.banknote.ws/COLLECTION/countries/EUR/SER/SER0054.htm"},
    "RSD:20":{front:"/assets/notes/banknotews/rsd/20-front.jpg",back:"/assets/notes/banknotews/rsd/20-back.jpg",imageStatus:'local-reference',imageSource:'Banknote Museum · banknote.ws',imageSourceUrl:"https://www.banknote.ws/COLLECTION/countries/EUR/SER/SER0055.htm"},
    "RSD:50":{front:"/assets/notes/banknotews/rsd/50-front.jpg",back:"/assets/notes/banknotews/rsd/50-back.jpg",imageStatus:'local-reference',imageSource:'Banknote Museum · banknote.ws',imageSourceUrl:"https://www.banknote.ws/COLLECTION/countries/EUR/SER/SER0056.htm"},
    "RSD:100":{front:"/assets/notes/banknotews/rsd/100-front.jpg",back:"/assets/notes/banknotews/rsd/100-back.jpg",imageStatus:'local-reference',imageSource:'Banknote Museum · banknote.ws',imageSourceUrl:"https://www.banknote.ws/COLLECTION/countries/EUR/SER/SER0057.htm"},
    "RSD:200":{front:"/assets/notes/banknotews/rsd/200-front.jpg",back:"/assets/notes/banknotews/rsd/200-back.jpg",imageStatus:'local-reference',imageSource:'Banknote Museum · banknote.ws',imageSourceUrl:"https://www.banknote.ws/COLLECTION/countries/EUR/SER/SER0058.htm"},
    "RSD:500":{front:"/assets/notes/banknotews/rsd/500-front.jpg",back:"/assets/notes/banknotews/rsd/500-back.jpg",imageStatus:'local-reference',imageSource:'Banknote Museum · banknote.ws',imageSourceUrl:"https://www.banknote.ws/COLLECTION/countries/EUR/SER/SER0059.htm"},
    "RSD:1000":{front:"/assets/notes/banknotews/rsd/1000-front.jpg",back:"/assets/notes/banknotews/rsd/1000-back.jpg",imageStatus:'local-reference',imageSource:'Banknote Museum · banknote.ws',imageSourceUrl:"https://www.banknote.ws/COLLECTION/countries/EUR/SER/SER0060.htm"},
    "RSD:2000":{front:"/assets/notes/banknotews/rsd/2000-front.jpg",back:"/assets/notes/banknotews/rsd/2000-back.jpg",imageStatus:'local-reference',imageSource:'Banknote Museum · banknote.ws',imageSourceUrl:"https://www.banknote.ws/COLLECTION/countries/EUR/SER/SER0061.htm"},
    "RSD:5000":{front:"/assets/notes/banknotews/rsd/5000-front.jpg",back:"/assets/notes/banknotews/rsd/5000-back.jpg",imageStatus:'local-reference',imageSource:'Banknote Museum · banknote.ws',imageSourceUrl:"https://www.banknote.ws/COLLECTION/countries/EUR/SER/SER0062.htm"},
    "ALL:200":{front:"/assets/notes/banknotews/all/200-front.jpg",back:"/assets/notes/banknotews/all/200-back.jpg",imageStatus:'local-reference',imageSource:'Banknote Museum · banknote.ws',imageSourceUrl:"https://www.banknote.ws/COLLECTION/countries/EUR/ALB/ALBW2017-0200.htm"},
    "ALL:500":{front:"/assets/notes/banknotews/all/500-front.jpg",back:"/assets/notes/banknotews/all/500-back.jpg",imageStatus:'local-reference',imageSource:'Banknote Museum · banknote.ws',imageSourceUrl:"https://www.banknote.ws/COLLECTION/countries/EUR/ALB/ALBW0077.htm"},
    "ALL:1000":{front:"/assets/notes/banknotews/all/1000-front.jpg",back:"/assets/notes/banknotews/all/1000-back.jpg",imageStatus:'local-reference',imageSource:'Banknote Museum · banknote.ws',imageSourceUrl:"https://www.banknote.ws/COLLECTION/countries/EUR/ALB/ALBW2019-1000.htm"},
    "ALL:2000":{front:"/assets/notes/banknotews/all/2000-front.jpg",back:"/assets/notes/banknotews/all/2000-back.jpg",imageStatus:'local-reference',imageSource:'Banknote Museum · banknote.ws',imageSourceUrl:"https://www.banknote.ws/COLLECTION/countries/EUR/ALB/ALBW0079.htm"},
    "ALL:5000":{front:"/assets/notes/banknotews/all/5000-front.jpg",back:"/assets/notes/banknotews/all/5000-back.jpg",imageStatus:'local-reference',imageSource:'Banknote Museum · banknote.ws',imageSourceUrl:"https://www.banknote.ws/COLLECTION/countries/EUR/ALB/ALBW2017-5000.htm"},
    "ALL:10000":{front:"/assets/notes/banknotews/all/10000-front.jpg",back:"/assets/notes/banknotews/all/10000-back.jpg",imageStatus:'local-reference',imageSource:'Banknote Museum · banknote.ws',imageSourceUrl:"https://www.banknote.ws/COLLECTION/countries/EUR/ALB/ALBW2019-10000.htm"},
    "BAM:10":{front:"/assets/notes/banknotews/bam/10-front.jpg",back:"/assets/notes/banknotews/bam/10-back.jpg",imageStatus:'local-reference',imageSource:'Banknote Museum · banknote.ws',imageSourceUrl:"https://www.banknote.ws/COLLECTION/countries/EUR/BIH/BIH0080.htm"},
    "BAM:20":{front:"/assets/notes/banknotews/bam/20-front.jpg",back:"/assets/notes/banknotews/bam/20-back.jpg",imageStatus:'local-reference',imageSource:'Banknote Museum · banknote.ws',imageSourceUrl:"https://www.banknote.ws/COLLECTION/countries/EUR/BIH/BIH0082.htm"},
    "BAM:50":{front:"/assets/notes/banknotews/bam/50-front.jpg",back:"/assets/notes/banknotews/bam/50-back.jpg",imageStatus:'local-reference',imageSource:'Banknote Museum · banknote.ws',imageSourceUrl:"https://www.banknote.ws/COLLECTION/countries/EUR/BIH/BIH0084.htm"},
    "BAM:100":{front:"/assets/notes/banknotews/bam/100-front.jpg",back:"/assets/notes/banknotews/bam/100-back.jpg",imageStatus:'local-reference',imageSource:'Banknote Museum · banknote.ws',imageSourceUrl:"https://www.banknote.ws/COLLECTION/countries/EUR/BIH/BIH0086.htm"},
    "BAM:200":{front:"/assets/notes/banknotews/bam/200-front.jpg",back:"/assets/notes/banknotews/bam/200-back.jpg",imageStatus:'local-reference',imageSource:'Banknote Museum · banknote.ws',imageSourceUrl:"https://www.banknote.ws/COLLECTION/countries/EUR/BIH/BIH0071.htm"},
    "MDL:1":{front:"/assets/notes/banknotews/mdl/1-front.jpg",back:"/assets/notes/banknotews/mdl/1-back.jpg",imageStatus:'local-reference',imageSource:'Banknote Museum · banknote.ws',imageSourceUrl:"https://www.banknote.ws/COLLECTION/countries/EUR/MOL/MOL0021.htm"},
    "MDL:5":{front:"/assets/notes/banknotews/mdl/5-front.jpg",back:"/assets/notes/banknotews/mdl/5-back.jpg",imageStatus:'local-reference',imageSource:'Banknote Museum · banknote.ws',imageSourceUrl:"https://www.banknote.ws/COLLECTION/countries/EUR/MOL/MOLW2015-005.htm"},
    "MDL:10":{front:"/assets/notes/banknotews/mdl/10-front.jpg",back:"/assets/notes/banknotews/mdl/10-back.jpg",imageStatus:'local-reference',imageSource:'Banknote Museum · banknote.ws',imageSourceUrl:"https://www.banknote.ws/COLLECTION/countries/EUR/MOL/MOL0022.htm"},
    "MDL:20":{front:"/assets/notes/banknotews/mdl/20-front.jpg",back:"/assets/notes/banknotews/mdl/20-back.jpg",imageStatus:'local-reference',imageSource:'Banknote Museum · banknote.ws',imageSourceUrl:"https://www.banknote.ws/COLLECTION/countries/EUR/MOL/MOL0023.htm"},
    "MDL:50":{front:"/assets/notes/banknotews/mdl/50-front.jpg",back:"/assets/notes/banknotews/mdl/50-back.jpg",imageStatus:'local-reference',imageSource:'Banknote Museum · banknote.ws',imageSourceUrl:"https://www.banknote.ws/COLLECTION/countries/EUR/MOL/MOL0024.htm"},
    "MDL:100":{front:"/assets/notes/banknotews/mdl/100-front.jpg",back:"/assets/notes/banknotews/mdl/100-back.jpg",imageStatus:'local-reference',imageSource:'Banknote Museum · banknote.ws',imageSourceUrl:"https://www.banknote.ws/COLLECTION/countries/EUR/MOL/MOL0025.htm"},
    "MDL:200":{front:"/assets/notes/banknotews/mdl/200-front.jpg",back:"/assets/notes/banknotews/mdl/200-back.jpg",imageStatus:'local-reference',imageSource:'Banknote Museum · banknote.ws',imageSourceUrl:"https://www.banknote.ws/COLLECTION/countries/EUR/MOL/MOL0026.htm"},
    "MDL:500":{front:"/assets/notes/banknotews/mdl/500-front.jpg",back:"/assets/notes/banknotews/mdl/500-back.jpg",imageStatus:'local-reference',imageSource:'Banknote Museum · banknote.ws',imageSourceUrl:"https://www.banknote.ws/COLLECTION/countries/EUR/MOL/MOL0027.htm"},
    "MDL:1000":{front:"/assets/notes/banknotews/mdl/1000-front.jpg",back:"/assets/notes/banknotews/mdl/1000-back.jpg",imageStatus:'local-reference',imageSource:'Banknote Museum · banknote.ws',imageSourceUrl:"https://www.banknote.ws/COLLECTION/countries/EUR/MOL/MOL0018.htm"},
    "BYN:5":{front:"/assets/notes/banknotews/byn/5-front.jpg",back:"/assets/notes/banknotews/byn/5-back.jpg",imageStatus:'local-reference',imageSource:'Banknote Museum · banknote.ws',imageSourceUrl:"https://www.banknote.ws/COLLECTION/countries/EUR/BLR/BLR0037.htm"},
    "BYN:10":{front:"/assets/notes/banknotews/byn/10-front.jpg",back:"/assets/notes/banknotews/byn/10-back.jpg",imageStatus:'local-reference',imageSource:'Banknote Museum · banknote.ws',imageSourceUrl:"https://www.banknote.ws/COLLECTION/countries/EUR/BLR/BLR0038.htm"},
    "BYN:20":{front:"/assets/notes/banknotews/byn/20-front.jpg",back:"/assets/notes/banknotews/byn/20-back.jpg",imageStatus:'local-reference',imageSource:'Banknote Museum · banknote.ws',imageSourceUrl:"https://www.banknote.ws/COLLECTION/countries/EUR/BLR/BLR0039.htm"},
    "BYN:50":{front:"/assets/notes/banknotews/byn/50-front.jpg",back:"/assets/notes/banknotews/byn/50-back.jpg",imageStatus:'local-reference',imageSource:'Banknote Museum · banknote.ws',imageSourceUrl:"https://www.banknote.ws/COLLECTION/countries/EUR/BLR/BLR0040.htm"},
    "BYN:100":{front:"/assets/notes/banknotews/byn/100-front.jpg",back:"/assets/notes/banknotews/byn/100-back.jpg",imageStatus:'local-reference',imageSource:'Banknote Museum · banknote.ws',imageSourceUrl:"https://www.banknote.ws/COLLECTION/countries/EUR/BLR/BLR0041.htm"},
    "BYN:200":{front:"/assets/notes/banknotews/byn/200-front.jpg",back:"/assets/notes/banknotews/byn/200-back.jpg",imageStatus:'local-reference',imageSource:'Banknote Museum · banknote.ws',imageSourceUrl:"https://www.banknote.ws/COLLECTION/countries/EUR/BLR/BLR0042.htm"},
    "BYN:500":{front:"/assets/notes/banknotews/byn/500-front.jpg",back:"/assets/notes/banknotews/byn/500-back.jpg",imageStatus:'local-reference',imageSource:'Banknote Museum · banknote.ws',imageSourceUrl:"https://www.banknote.ws/COLLECTION/countries/EUR/BLR/BLR0043.htm"},
    "UAH:20":{front:"/assets/notes/banknotews/uah/20-front.jpg",back:"/assets/notes/banknotews/uah/20-back.jpg",imageStatus:'local-reference',imageSource:'Banknote Museum · banknote.ws',imageSourceUrl:"https://www.banknote.ws/COLLECTION/countries/EUR/UKR/UKRW0138.htm"},
    "UAH:50":{front:"/assets/notes/banknotews/uah/50-front.jpg",back:"/assets/notes/banknotews/uah/50-back.jpg",imageStatus:'local-reference',imageSource:'Banknote Museum · banknote.ws',imageSourceUrl:"https://www.banknote.ws/COLLECTION/countries/EUR/UKR/UKRW0139.htm"},
    "UAH:100":{front:"/assets/notes/banknotews/uah/100-front.jpg",back:"/assets/notes/banknotews/uah/100-back.jpg",imageStatus:'local-reference',imageSource:'Banknote Museum · banknote.ws',imageSourceUrl:"https://www.banknote.ws/COLLECTION/countries/EUR/UKR/UKRW0140.htm"},
    "UAH:200":{front:"/assets/notes/banknotews/uah/200-front.jpg",back:"/assets/notes/banknotews/uah/200-back.jpg",imageStatus:'local-reference',imageSource:'Banknote Museum · banknote.ws',imageSourceUrl:"https://www.banknote.ws/COLLECTION/countries/EUR/UKR/UKRW0141.htm"},
    "UAH:500":{front:"/assets/notes/banknotews/uah/500-front.jpg",back:"/assets/notes/banknotews/uah/500-back.jpg",imageStatus:'local-reference',imageSource:'Banknote Museum · banknote.ws',imageSourceUrl:"https://www.banknote.ws/COLLECTION/countries/EUR/UKR/UKRW0142.htm"},
    "UAH:1000":{front:"/assets/notes/banknotews/uah/1000-front.jpg",back:"/assets/notes/banknotews/uah/1000-back.jpg",imageStatus:'local-reference',imageSource:'Banknote Museum · banknote.ws',imageSourceUrl:"https://www.banknote.ws/COLLECTION/countries/EUR/UKR/UKRW0143.htm"}
  };
  const previousFetch=window.fetch.bind(window);
  window.fetch=async(...args)=>{
    const req=args[0],url=typeof req==='string'?req:req?.url||'';
    const response=await previousFetch(...args);
    if(!url.includes('/data/notes.json')) return response;
    const data=await response.clone().json();
    for(const n of data){const x=O[`${n.currency}:${Number(n.value)}`];if(x)Object.assign(n,x);}
    return new Response(JSON.stringify(data),{status:response.status,statusText:response.statusText,headers:{'Content-Type':'application/json; charset=utf-8'}});
  };
})();
