(()=>{
 const defs=[
  {id:'BHS',name:'Bahamas',flag:'🇧🇸',continent:'North America',region:'Caraíbas',currency:'BSD',capital:'Nassau',population:'≈ 400 mil',language:'Inglês',history:[['1966–hoje','Dólar das Bahamas (BSD), à paridade com o dólar dos EUA']]},
  {id:'BRB',name:'Barbados',flag:'🇧🇧',continent:'North America',region:'Caraíbas',currency:'BBD',capital:'Bridgetown',population:'≈ 280 mil',language:'Inglês',history:[['1973–hoje','Dólar de Barbados (BBD)']]},
  {id:'JAM',name:'Jamaica',flag:'🇯🇲',continent:'North America',region:'Caraíbas',currency:'JMD',capital:'Kingston',population:'≈ 2,8 milhões',language:'Inglês / Patois jamaicano',history:[['1969–hoje','Dólar jamaicano (JMD)']]},
  {id:'TTO',name:'Trinidad e Tobago',flag:'🇹🇹',continent:'North America',region:'Caraíbas',currency:'TTD',capital:'Port of Spain',population:'≈ 1,5 milhões',language:'Inglês',history:[['1964–hoje','Dólar de Trinidad e Tobago (TTD)']]},
  {id:'HTI',name:'Haiti',flag:'🇭🇹',continent:'North America',region:'Caraíbas',currency:'HTG',capital:'Porto Príncipe',population:'≈ 12 milhões',language:'Crioulo haitiano / Francês',history:[['1813–hoje','Gourde haitiano (HTG)']]},
  {id:'DOM',name:'República Dominicana',flag:'🇩🇴',continent:'North America',region:'Caraíbas',currency:'DOP',capital:'Santo Domingo',population:'≈ 11,5 milhões',language:'Espanhol',history:[['1947–hoje','Peso dominicano (DOP)']]},
  {id:'CUB',name:'Cuba',flag:'🇨🇺',continent:'North America',region:'Caraíbas',currency:'CUP',capital:'Havana',population:'≈ 10 milhões',language:'Espanhol',history:[['1857–hoje','Peso cubano (CUP)'],['1994–2021','Coexistência com o peso convertível (CUC)'],['2021–hoje','CUP como única moeda nacional em circulação geral']]},
  {id:'BLZ',name:'Belize',flag:'🇧🇿',continent:'North America',region:'Caraíbas',currency:'BZD',capital:'Belmopan',population:'≈ 420 mil',language:'Inglês / Crioulo belizenho',history:[['1974–hoje','Dólar de Belize (BZD), ligado ao dólar dos EUA']]},

  {id:'ATG',name:'Antígua e Barbuda',flag:'🇦🇬',continent:'North America',region:'Caraíbas',currency:'XCD',capital:"Saint John's",population:'≈ 100 mil',language:'Inglês',history:[['1965–hoje','Dólar das Caraíbas Orientais (XCD)']]},
  {id:'DMA',name:'Dominica',flag:'🇩🇲',continent:'North America',region:'Caraíbas',currency:'XCD',capital:'Roseau',population:'≈ 70 mil',language:'Inglês / Crioulo francês',history:[['1965–hoje','Dólar das Caraíbas Orientais (XCD)']]},
  {id:'GRD',name:'Granada',flag:'🇬🇩',continent:'North America',region:'Caraíbas',currency:'XCD',capital:"Saint George's",population:'≈ 125 mil',language:'Inglês',history:[['1965–hoje','Dólar das Caraíbas Orientais (XCD)']]},
  {id:'KNA',name:'São Cristóvão e Neves',flag:'🇰🇳',continent:'North America',region:'Caraíbas',currency:'XCD',capital:'Basseterre',population:'≈ 50 mil',language:'Inglês',history:[['1965–hoje','Dólar das Caraíbas Orientais (XCD)']]},
  {id:'LCA',name:'Santa Lúcia',flag:'🇱🇨',continent:'North America',region:'Caraíbas',currency:'XCD',capital:'Castries',population:'≈ 180 mil',language:'Inglês / Crioulo francês',history:[['1965–hoje','Dólar das Caraíbas Orientais (XCD)']]},
  {id:'VCT',name:'São Vicente e Granadinas',flag:'🇻🇨',continent:'North America',region:'Caraíbas',currency:'XCD',capital:'Kingstown',population:'≈ 100 mil',language:'Inglês',history:[['1965–hoje','Dólar das Caraíbas Orientais (XCD)']]},
  {id:'AIA',name:'Anguila',flag:'🇦🇮',continent:'North America',region:'Caraíbas',currency:'XCD',capital:'The Valley',population:'≈ 16 mil',language:'Inglês',history:[['1965–hoje','Dólar das Caraíbas Orientais (XCD)']]},
  {id:'MSR',name:'Montserrat',flag:'🇲🇸',continent:'North America',region:'Caraíbas',currency:'XCD',capital:'Brades (de facto)',population:'≈ 5 mil',language:'Inglês',history:[['1965–hoje','Dólar das Caraíbas Orientais (XCD)']]},

  {id:'ABW',name:'Aruba',flag:'🇦🇼',continent:'North America',region:'Caraíbas',currency:'AWG',capital:'Oranjestad',population:'≈ 110 mil',language:'Papiamento / Neerlandês',history:[['1986–hoje','Florim arubano (AWG)']]},
  {id:'CYM',name:'Ilhas Caimão',flag:'🇰🇾',continent:'North America',region:'Caraíbas',currency:'KYD',capital:'George Town',population:'≈ 75 mil',language:'Inglês',history:[['1972–hoje','Dólar das Ilhas Caimão (KYD)']]},
  {id:'BMU',name:'Bermudas',flag:'🇧🇲',continent:'North America',region:'Atlântico/Caraíbas',currency:'BMD',capital:'Hamilton',population:'≈ 64 mil',language:'Inglês',history:[['1970–hoje','Dólar das Bermudas (BMD), à paridade com o dólar dos EUA']]},

  {id:'PRI',name:'Porto Rico',flag:'🇵🇷',continent:'North America',region:'Caraíbas',currency:'USD',capital:'San Juan',population:'≈ 3,2 milhões',language:'Espanhol / Inglês',history:[['1898–hoje','Dólar dos Estados Unidos (USD)']]},
  {id:'VIR',name:'Ilhas Virgens Americanas',flag:'🇻🇮',continent:'North America',region:'Caraíbas',currency:'USD',capital:'Charlotte Amalie',population:'≈ 90 mil',language:'Inglês',history:[['1917–hoje','Dólar dos Estados Unidos (USD)']]},
  {id:'VGB',name:'Ilhas Virgens Britânicas',flag:'🇻🇬',continent:'North America',region:'Caraíbas',currency:'USD',capital:'Road Town',population:'≈ 40 mil',language:'Inglês',history:[['século XX–hoje','Dólar dos Estados Unidos (USD)']]},
  {id:'TCA',name:'Ilhas Turcas e Caicos',flag:'🇹🇨',continent:'North America',region:'Caraíbas',currency:'USD',capital:'Cockburn Town',population:'≈ 50 mil',language:'Inglês',history:[['século XX–hoje','Dólar dos Estados Unidos (USD)']]},
  {id:'BES',name:'Caribe Neerlandês',flag:'🇧🇶',continent:'North America',region:'Caraíbas',currency:'USD',capital:'—',population:'≈ 30 mil',language:'Neerlandês / Papiamento / Inglês',history:[['2011–hoje','Dólar dos Estados Unidos (USD) em Bonaire, Santo Eustáquio e Saba']]},
  {id:'GLP',name:'Guadalupe',flag:'🇬🇵',continent:'North America',region:'Caraíbas',currency:'EUR',capital:'Basse-Terre',population:'≈ 380 mil',language:'Francês / Crioulo',history:[['1999/2002–hoje','Euro (EUR)']]},
  {id:'MTQ',name:'Martinica',flag:'🇲🇶',continent:'North America',region:'Caraíbas',currency:'EUR',capital:'Fort-de-France',population:'≈ 350 mil',language:'Francês / Crioulo',history:[['1999/2002–hoje','Euro (EUR)']]},
  {id:'BLM',name:'São Bartolomeu',flag:'🇧🇱',continent:'North America',region:'Caraíbas',currency:'EUR',capital:'Gustavia',population:'≈ 11 mil',language:'Francês',history:[['1999/2002–hoje','Euro (EUR)']]},
  {id:'MAF',name:'São Martinho (parte francesa)',flag:'🇲🇫',continent:'North America',region:'Caraíbas',currency:'EUR',capital:'Marigot',population:'≈ 32 mil',language:'Francês',history:[['1999/2002–hoje','Euro (EUR)']]}
 ];
 const currencies={
  BSD:{name:'Dólar das Bahamas',symbol:'B$',group:'Bahamas',source:'Central Bank of The Bahamas',material:'Papel / polímero',notes:[1,3,5,10,20,50,100],countries:['BHS'],focus:false,rate:1.17},
  BBD:{name:'Dólar de Barbados',symbol:'Bds$',group:'Barbados',source:'Central Bank of Barbados',material:'Polímero',notes:[2,5,10,20,50,100],countries:['BRB'],focus:false,rate:2.34},
  JMD:{name:'Dólar jamaicano',symbol:'J$',group:'Jamaica',source:'Bank of Jamaica',material:'Polímero',notes:[50,100,500,1000,2000,5000],countries:['JAM'],focus:false,rate:185},
  TTD:{name:'Dólar de Trinidad e Tobago',symbol:'TT$',group:'Trinidad e Tobago',source:'Central Bank of Trinidad and Tobago',material:'Polímero',notes:[1,5,10,20,50,100],countries:['TTO'],focus:false,rate:7.9},
  HTG:{name:'Gourde haitiano',symbol:'G',group:'Haiti',source:'Banque de la République d’Haïti',material:'Papel / polímero',notes:[10,25,50,100,250,500,1000],countries:['HTI'],focus:false,rate:153},
  DOP:{name:'Peso dominicano',symbol:'RD$',group:'República Dominicana',source:'Banco Central de la República Dominicana',material:'Papel',notes:[50,100,200,500,1000,2000],countries:['DOM'],focus:false,rate:74},
  CUP:{name:'Peso cubano',symbol:'$',group:'Cuba',source:'Banco Central de Cuba',material:'Papel',notes:[1,3,5,10,20,50,100,200,500,1000,2000,5000],countries:['CUB'],focus:false,rate:140},
  BZD:{name:'Dólar de Belize',symbol:'BZ$',group:'Belize',source:'Central Bank of Belize',material:'Polímero',notes:[2,5,10,20,50,100],countries:['BLZ'],focus:false,rate:2.34},
  XCD:{name:'Dólar das Caraíbas Orientais',symbol:'EC$',group:'União Monetária das Caraíbas Orientais',source:'Eastern Caribbean Central Bank',material:'Polímero',notes:[5,10,20,50,100],countries:['AIA','ATG','DMA','GRD','KNA','LCA','MSR','VCT'],focus:false,rate:3.16},
  AWG:{name:'Florim arubano',symbol:'Afl.',group:'Aruba',source:'Centrale Bank van Aruba',material:'Papel',notes:[10,25,50,100,200],countries:['ABW'],focus:false,rate:2.09},
  KYD:{name:'Dólar das Ilhas Caimão',symbol:'CI$',group:'Ilhas Caimão',source:'Cayman Islands Monetary Authority',material:'Papel',notes:[1,5,10,25,50,100],countries:['CYM'],focus:false,rate:0.98},
  BMD:{name:'Dólar das Bermudas',symbol:'BD$',group:'Bermudas',source:'Bermuda Monetary Authority',material:'Papel / polímero',notes:[2,5,10,20,50,100],countries:['BMU'],focus:false,rate:1.17}
 };
 const iso={'044':'BHS','052':'BRB','388':'JAM','780':'TTO','332':'HTI','214':'DOM','192':'CUB','084':'BLZ','028':'ATG','212':'DMA','308':'GRD','659':'KNA','662':'LCA','670':'VCT','660':'AIA','500':'MSR','533':'ABW','136':'CYM','060':'BMU','630':'PRI','850':'VIR','092':'VGB','796':'TCA','535':'BES','312':'GLP','474':'MTQ','652':'BLM','663':'MAF'};
 const official={BSD:'https://www.centralbankbahamas.com/',BBD:'https://www.centralbank.org.bb/',JMD:'https://boj.org.jm/',TTD:'https://www.central-bank.org.tt/',HTG:'https://www.brh.ht/',DOP:'https://www.bancentral.gov.do/',CUP:'https://www.bc.gob.cu/',BZD:'https://www.centralbank.org.bz/',XCD:'https://www.eccb-centralbank.org/',AWG:'https://www.cbaruba.org/',KYD:'https://www.cima.ky/',BMD:'https://www.bma.bm/'};
 const local=new Set(Object.keys(currencies));
 const oldFetch=window.fetch.bind(window);
 window.fetch=async(...args)=>{const req=args[0],url=typeof req==='string'?req:req?.url||'';const r=await oldFetch(...args);
  if(url.includes('/data/countries.json')){const data=await r.clone().json();for(const c of defs){const x=data.find(v=>v.id===c.id);x?Object.assign(x,c):data.push(c)}return new Response(JSON.stringify(data),{status:r.status,statusText:r.statusText,headers:{'Content-Type':'application/json; charset=utf-8'}})}
  if(url.includes('/data/currencies.json')){const data=await r.clone().json();for(const [code,def] of Object.entries(currencies))data[code]=Object.assign({},data[code]||{},def);for(const [code,extra] of Object.entries({USD:['PRI','VIR','VGB','TCA','BES'],EUR:['GLP','MTQ','BLM','MAF']})){if(data[code])data[code].countries=[...new Set([...(data[code].countries||[]),...extra])]}return new Response(JSON.stringify(data),{status:r.status,statusText:r.statusText,headers:{'Content-Type':'application/json; charset=utf-8'}})}
  if(url.includes('/data/iso-map.json')){const data=await r.clone().json();Object.assign(data,iso);return new Response(JSON.stringify(data),{status:r.status,statusText:r.statusText,headers:{'Content-Type':'application/json; charset=utf-8'}})}
  if(!url.includes('/data/notes.json'))return r;const data=await r.clone().json();for(const [code,def] of Object.entries(currencies))for(const value of def.notes){let n=data.find(x=>x.currency===code&&Number(x.value)===Number(value));if(!n){n={currency:code,value};data.push(n)}Object.assign(n,{status:'circulating',statusLabel:'Em circulação',source:def.source,material:def.material,front:`/assets/notes/banknotews/${code.toLowerCase()}/${value}-front.jpg`,back:`/assets/notes/banknotews/${code.toLowerCase()}/${value}-back.jpg`,imageStatus:'local-reference',imageSource:'Bank Note Museum · cópia local',officialUrl:official[code],officialLabel:`Ver ${code} na fonte oficial`})}return new Response(JSON.stringify(data),{status:r.status,statusText:r.statusText,headers:{'Content-Type':'application/json; charset=utf-8'}})};
 window.NOTAS_CARIBBEAN_CODES=local;
})();
