// Contexto editorial das moedas · Notas do Mundo
// O fallback garante contexto e ligação à Wikipédia para qualquer moeda da base.
(()=>{
 const C={
  XPF:{wiki:'https://en.wikipedia.org/wiki/CFP_franc',overview:'O franco CFP é a moeda utilizada na Polinésia Francesa, Nova Caledónia e Wallis e Futuna. O código ISO é XPF e a emissão é assegurada pelo Institut d’Émission d’Outre-Mer (IEOM).',history:'Criado em dezembro de 1945, no contexto monetário do pós-guerra, o franco CFP teve inicialmente diferentes apresentações territoriais. Desde 1967 é emitido pelo IEOM. A sigla CFP, originalmente ligada às colónias francesas do Pacífico, passou oficialmente em 2022 a significar «Collectivités françaises du Pacifique». A moeda mantém uma paridade fixa com o euro, na continuidade da antiga ligação ao franco francês.',sourceLabel:'Wikipédia · CFP franc'},
  XOF:{wiki:'https://en.wikipedia.org/wiki/West_African_CFA_franc',overview:'O franco CFA da África Ocidental (XOF) é a moeda comum de oito Estados da União Económica e Monetária da África Ocidental e é emitido pelo BCEAO.',history:'Foi criado em 1945. Atualmente é utilizado no Benim, Burkina Faso, Costa do Marfim, Guiné-Bissau, Mali, Níger, Senegal e Togo. É nominalmente dividido em 100 cêntimos, embora não existam denominações correntes em cêntimos, e mantém uma paridade fixa com o euro.',sourceLabel:'Wikipédia · West African CFA franc'},
  XAF:{wiki:'https://en.wikipedia.org/wiki/Central_African_CFA_franc',overview:'O franco CFA da África Central (XAF) é utilizado por seis Estados da CEMAC e é emitido pelo Banque des États de l’Afrique Centrale (BEAC).',history:'Introduzido em 1945 nos territórios franceses da África Equatorial, continuou a ser usado após as independências. Hoje circula nos Camarões, República Centro-Africana, Chade, República do Congo, Guiné Equatorial e Gabão. Tal como o XOF, está ligado ao euro por uma taxa fixa, mas as duas moedas não são intercambiáveis.',sourceLabel:'Wikipédia · Central African CFA franc'},
  XCD:{wiki:'https://en.wikipedia.org/wiki/Eastern_Caribbean_dollar',overview:'O dólar das Caraíbas Orientais (XCD) é a moeda de vários membros da Organização dos Estados das Caraíbas Orientais e é emitido pelo Eastern Caribbean Central Bank.',history:'Sucedeu ao dólar das Índias Ocidentais Britânicas e existe desde 1965. Desde 1976 mantém uma paridade fixa com o dólar dos Estados Unidos de 1 USD = 2,70 XCD. É uma das moedas partilhadas mais características das Caraíbas.',sourceLabel:'Wikipédia · Eastern Caribbean dollar'},
  XCG:{wiki:'https://en.wikipedia.org/wiki/Caribbean_guilder',overview:'O florim das Caraíbas (XCG) é a moeda de Curaçau e Sint Maarten e é emitido pelo Centrale Bank van Curaçao en Sint Maarten.',history:'Entrou em circulação em 31 de março de 2025 e substituiu o florim das Antilhas Neerlandesas. É uma moeda nova, criada especificamente para os dois países constituintes do Reino dos Países Baixos, e mantém ligação cambial ao dólar dos Estados Unidos.',sourceLabel:'Wikipédia · Caribbean guilder'},
  EUR:{wiki:'https://en.wikipedia.org/wiki/Euro',overview:'O euro é a moeda comum dos países da área do euro e uma das principais moedas de reserva e de pagamentos internacionais.',history:'Foi lançado como moeda contabilística em 1999 e as notas e moedas entraram em circulação em 2002. É administrado pelo Eurosistema, formado pelo Banco Central Europeu e pelos bancos centrais nacionais dos países participantes.',sourceLabel:'Wikipédia · Euro'},
  USD:{wiki:'https://en.wikipedia.org/wiki/United_States_dollar',overview:'O dólar dos Estados Unidos é a moeda oficial dos EUA e a principal moeda de reserva internacional, sendo também utilizado oficialmente ou de facto em vários outros territórios e países.',history:'A unidade monetária foi estabelecida pelo Coinage Act de 1792. Ao longo do século XX o dólar tornou-se a principal referência do sistema monetário internacional e permanece central nas reservas cambiais, comércio e mercados financeiros.',sourceLabel:'Wikipédia · United States dollar'},
  GBP:{wiki:'https://en.wikipedia.org/wiki/Pound_sterling',overview:'A libra esterlina é a moeda do Reino Unido e uma das moedas ainda em circulação com história contínua mais longa.',history:'A sua origem remonta ao sistema monetário anglo-saxónico. A libra foi decimalizada em 1971 e, nas últimas décadas, o Bank of England substituiu progressivamente as notas de papel por notas de polímero.',sourceLabel:'Wikipédia · Pound sterling'},
  CHF:{wiki:'https://en.wikipedia.org/wiki/Swiss_franc',overview:'O franco suíço é a moeda da Suíça e do Liechtenstein e é frequentemente associado a estabilidade financeira e procura de refúgio.',history:'Foi introduzido em 1850 para uniformizar as numerosas moedas que circulavam na Confederação Suíça. A emissão de notas é hoje responsabilidade do Swiss National Bank.',sourceLabel:'Wikipédia · Swiss franc'},
  JPY:{wiki:'https://en.wikipedia.org/wiki/Japanese_yen',overview:'O iene é a moeda do Japão e uma das principais moedas de reserva e negociação do mundo.',history:'Foi introduzido em 1871 durante a modernização monetária da era Meiji, substituindo o complexo sistema de moedas do período feudal. O Bank of Japan é o banco central emissor.',sourceLabel:'Wikipédia · Japanese yen'},
  CNY:{wiki:'https://en.wikipedia.org/wiki/Renminbi',overview:'O renminbi é a moeda da República Popular da China; yuan é o nome da principal unidade de conta. O seu código internacional é CNY.',history:'O renminbi foi introduzido pelo People’s Bank of China em 1948, antes da fundação da República Popular. A moeda passou por várias famílias de notas e tornou-se progressivamente mais relevante no comércio e nas reservas internacionais.',sourceLabel:'Wikipédia · Renminbi'},
  AUD:{wiki:'https://en.wikipedia.org/wiki/Australian_dollar',overview:'O dólar australiano é a moeda da Austrália e de vários territórios associados e tem forte presença nos mercados da região Ásia-Pacífico.',history:'Substituiu a libra australiana em 1966, quando a Austrália adotou um sistema monetário decimal. Em 1988 o país foi pioneiro na emissão de uma nota moderna de polímero e posteriormente converteu toda a família para esse suporte.',sourceLabel:'Wikipédia · Australian dollar'},
  NZD:{wiki:'https://en.wikipedia.org/wiki/New_Zealand_dollar',overview:'O dólar neozelandês é a moeda da Nova Zelândia e também serve de referência monetária a alguns territórios do Pacífico.',history:'Foi introduzido em 1967, substituindo a libra neozelandesa no processo de decimalização. As notas atuais são emitidas pelo Reserve Bank of New Zealand e usam polímero.',sourceLabel:'Wikipédia · New Zealand dollar'},
  CAD:{wiki:'https://en.wikipedia.org/wiki/Canadian_dollar',overview:'O dólar canadiano é a moeda do Canadá e uma das moedas mais negociadas nos mercados cambiais internacionais.',history:'A adoção de uma moeda decimal em dólares consolidou-se no Canadá durante o século XIX. O Bank of Canada, criado em 1934, tornou-se o emissor das notas nacionais; desde 2011 as principais denominações são produzidas em polímero.',sourceLabel:'Wikipédia · Canadian dollar'},
  INR:{wiki:'https://en.wikipedia.org/wiki/Indian_rupee',overview:'A rupia indiana é a moeda da Índia e é emitida sobretudo pelo Reserve Bank of India.',history:'A palavra «rupia» deriva de uma longa tradição monetária do subcontinente indiano. A atual rupia decimal resulta das reformas posteriores à independência e, desde 2010, utiliza o símbolo ₹.',sourceLabel:'Wikipédia · Indian rupee'},
  HKD:{wiki:'https://en.wikipedia.org/wiki/Hong_Kong_dollar',overview:'O dólar de Hong Kong é a moeda da Região Administrativa Especial de Hong Kong e possui um sistema de emissão invulgar, no qual vários bancos comerciais emitem notas sob supervisão monetária.',history:'O dólar de Hong Kong surgiu no século XIX num território onde circulavam várias moedas de prata. Atualmente funciona num regime de currency board e mantém uma banda de ligação ao dólar dos Estados Unidos.',sourceLabel:'Wikipédia · Hong Kong dollar'},
  SGD:{wiki:'https://en.wikipedia.org/wiki/Singapore_dollar',overview:'O dólar de Singapura é a moeda da cidade-Estado e uma moeda relevante de um dos principais centros financeiros da Ásia.',history:'Foi introduzido em 1967 após o fim da união monetária com a Malásia e o Brunei. A emissão é hoje administrada pela Monetary Authority of Singapore.',sourceLabel:'Wikipédia · Singapore dollar'},
  BRL:{wiki:'https://en.wikipedia.org/wiki/Brazilian_real',overview:'O real é a moeda do Brasil e foi criado no âmbito do Plano Real para estabilizar a economia após um longo período de inflação elevada.',history:'Entrou em circulação em 1 de julho de 1994, substituindo o cruzeiro real. O nome recupera uma designação monetária histórica usada no Brasil durante séculos.',sourceLabel:'Wikipédia · Brazilian real'},
  MXN:{wiki:'https://en.wikipedia.org/wiki/Mexican_peso',overview:'O peso mexicano é a moeda do México e deriva diretamente da tradição do peso espanhol e do dólar espanhol.',history:'O peso tem raízes coloniais e foi durante séculos uma moeda de grande circulação internacional. O atual «nuevo peso», introduzido em 1993, retirou três zeros à unidade anterior; o código ISO é MXN.',sourceLabel:'Wikipédia · Mexican peso'},
  ZAR:{wiki:'https://en.wikipedia.org/wiki/South_African_rand',overview:'O rand é a moeda da África do Sul e também desempenha um papel regional através da Área Monetária Comum da África Austral.',history:'Foi introduzido em 1961, quando a África do Sul substituiu a libra sul-africana e adotou um sistema decimal. O nome deriva de Witwatersrand, região ligada à história mineira do país.',sourceLabel:'Wikipédia · South African rand'},
  TRY:{wiki:'https://en.wikipedia.org/wiki/Turkish_lira',overview:'A lira turca é a moeda da Turquia e é emitida pelo Türkiye Cumhuriyet Merkez Bankası.',history:'A lira otomana do século XIX antecedeu a moderna lira turca. Em 2005 foi introduzida a «nova lira turca», retirando seis zeros à moeda anterior; em 2009 o nome voltou simplesmente a «lira turca».',sourceLabel:'Wikipédia · Turkish lira'},
  KRW:{wiki:'https://en.wikipedia.org/wiki/South_Korean_won',overview:'O won sul-coreano é a moeda da República da Coreia e é emitido pelo Bank of Korea.',history:'A atual unidade foi reintroduzida em 1962, substituindo o hwan. O nome «won» pertence a uma família histórica de termos monetários do Leste Asiático relacionados com a ideia de moeda redonda.',sourceLabel:'Wikipédia · South Korean won'},
  BDT:{wiki:'https://en.wikipedia.org/wiki/Bangladeshi_taka',overview:'O taka é a moeda do Bangladesh. O nome tem raízes históricas profundas no subcontinente e a emissão moderna começou após a independência do país.',history:'O Bangladesh introduziu o taka em 1972, substituindo a rupia paquistanesa. O Bangladesh Bank emite a maioria das notas, enquanto algumas pequenas denominações podem ser emitidas pelo governo.',sourceLabel:'Wikipédia · Bangladeshi taka'},
  XPF_NOTE:{wiki:'https://en.wikipedia.org/wiki/Banknotes_of_the_CFP_franc'}
 };
 function fallback(code,c,members){
   const names=(members||[]).map(x=>x.name).filter(Boolean);
   const where=names.length===1?names[0]:names.length>1?names.join(', '):c.group||'a respetiva área monetária';
   const q=encodeURIComponent(`${c.name} currency`);
   return {
     wiki:`https://en.wikipedia.org/wiki/Special:Search?search=${q}`,
     overview:`${c.name} (${code}) é a moeda associada a ${where}. A entidade emissora ou monetária indicada na base é ${c.source}.`,
     history:`A família representada nesta aplicação reúne ${c.notes?.length||0} denominações. A ligação abaixo permite consultar na Wikipédia a história da unidade monetária, reformas, moedas anteriores e evolução do sistema de emissão.`,
     sourceLabel:`Wikipédia · procurar ${c.name}`
   };
 }
 window.CURRENCY_CONTEXT=C;
 window.getCurrencyContext=(code,c,members)=>C[code]||fallback(code,c,members);
})();
