(() => {
  const INFO={
    'USD:100':{front:{title:'Benjamin Franklin',summary:'Um dos Pais Fundadores dos Estados Unidos, diplomata, cientista, inventor e signatário da Declaração de Independência.',more:'Franklin teve um papel central na diplomacia da independência norte-americana e foi também uma figura marcante do Iluminismo.',wiki:'https://pt.wikipedia.org/wiki/Benjamin_Franklin'},back:{title:'Independence Hall · Filadélfia',summary:'Edifício histórico onde foram debatidas e adotadas a Declaração de Independência e a Constituição dos Estados Unidos.',more:'O edifício, na Pensilvânia, é um dos lugares simbólicos da fundação política dos Estados Unidos.',wiki:'https://pt.wikipedia.org/wiki/Independence_Hall'}},
    'CLP:1000':{front:{title:'Ignacio Carrera Pinto',summary:'Capitão do Exército chileno, lembrado sobretudo pela Batalha de La Concepción durante a Guerra do Pacífico.',more:'Carrera Pinto comandou a guarnição chilena em La Concepción, no Peru, em julho de 1882. A sua figura tornou-se um símbolo militar no Chile.',wiki:'https://pt.wikipedia.org/wiki/Ignacio_Carrera_Pinto'},back:{title:'Parque Nacional Torres del Paine · Guanaco',summary:'Paisagem do Parque Nacional Torres del Paine, na Patagónia chilena, acompanhada por um guanaco.',more:'Torres del Paine é uma das áreas protegidas mais emblemáticas do Chile. O guanaco é um camelídeo nativo da América do Sul.',wiki:'https://pt.wikipedia.org/wiki/Parque_Nacional_Torres_del_Paine'}},
    'CLP:2000':{front:{title:'Manuel Rodríguez Erdoíza',summary:'Advogado, guerrilheiro e figura destacada do processo de independência do Chile.',more:'Rodríguez ficou conhecido pelas ações clandestinas e de resistência durante a Reconquista espanhola.',wiki:'https://pt.wikipedia.org/wiki/Manuel_Rodr%C3%ADguez_Erdo%C3%ADza'},back:{title:'Reserva Nacional Nalcas · Loro choroy',summary:'Paisagem da Reserva Nacional Nalcas, com araucária e loro choroy.',more:'A reserva protege ecossistemas andinos e bosques nativos da Região da Araucanía.',wiki:'https://pt.wikipedia.org/wiki/Reserva_Nacional_Nalcas'}},
    'CLP:5000':{front:{title:'Gabriela Mistral',summary:'Poeta, diplomata e educadora chilena, vencedora do Prémio Nobel da Literatura em 1945.',more:'Foi a primeira personalidade latino-americana a receber o Nobel da Literatura.',wiki:'https://pt.wikipedia.org/wiki/Gabriela_Mistral'},back:{title:'Parque Nacional La Campana · Tucúquere',summary:'Paisagem do Parque Nacional La Campana, com palmeiras chilenas e um tucúquere.',more:'La Campana protege uma importante população de palmeira-chilena.',wiki:'https://pt.wikipedia.org/wiki/Parque_Nacional_La_Campana'}},
    'CLP:10000':{front:{title:'Arturo Prat Chacón',summary:'Oficial da Marinha do Chile e uma das figuras históricas mais conhecidas do país.',more:'Prat morreu durante o Combate Naval de Iquique, em 21 de maio de 1879.',wiki:'https://pt.wikipedia.org/wiki/Arturo_Prat'},back:{title:'Parque Nacional Alberto de Agostini · Cóndor',summary:'Paisagem glacial do extremo sul chileno acompanhada por um cóndor-dos-Andes.',more:'O parque situa-se na Terra do Fogo e reúne montanhas, fiordes e glaciares.',wiki:'https://pt.wikipedia.org/wiki/Parque_Nacional_Alberto_de_Agostini'}},
    'CLP:20000':{front:{title:'Andrés Bello',summary:'Humanista, jurista, filósofo e educador, figura fundamental da vida intelectual chilena do século XIX.',more:'Bello foi o primeiro reitor da Universidade do Chile e principal autor do Código Civil chileno de 1855.',wiki:'https://pt.wikipedia.org/wiki/Andr%C3%A9s_Bello'},back:{title:'Monumento Natural Salar de Surire · Flamingos',summary:'Paisagem altiplânica do Salar de Surire, conhecida pelas suas populações de flamingos.',more:'É uma área protegida da Região de Arica e Parinacota e habitat importante para aves aquáticas andinas.',wiki:'https://pt.wikipedia.org/wiki/Monumento_natural_Salar_de_Surire'}},
    'ARS:100':{front:{title:'María Eva Duarte de Perón',summary:'Eva Perón foi uma das figuras políticas e sociais mais influentes da Argentina do século XX.',more:'A nota homenageia a sua projeção pública e o seu papel na história social argentina.',wiki:'https://pt.wikipedia.org/wiki/Eva_Per%C3%B3n'},back:{title:'Voto feminino e Escola de Enfermagem',summary:'A composição evoca a conquista do voto feminino na Argentina e a Escola de Enfermagem.',more:'A Lei 13.010, aprovada em 1947, reconheceu às mulheres argentinas os mesmos direitos políticos dos homens.',wiki:'https://pt.wikipedia.org/wiki/Sufr%C3%A1gio_feminino'}},
    'ARS:200':{front:{title:'Martín Miguel de Güemes e Juana Azurduy',summary:'Dois protagonistas das lutas de independência sul-americanas.',more:'Güemes destacou-se na defesa do noroeste argentino; Azurduy combateu nas guerras de independência.',wiki:'https://pt.wikipedia.org/wiki/Juana_Azurduy_de_Padilla'},back:{title:'Campanha gaúcha',summary:'Cena evocativa das forças de cavalaria que combateram no norte argentino.',more:'A Guerra Gaucha foi decisiva para conter avanços realistas vindos do Alto Peru.',wiki:'https://pt.wikipedia.org/wiki/Mart%C3%ADn_Miguel_de_G%C3%BCemes'}},
    'ARS:500':{front:{title:'María Remedios del Valle e Manuel Belgrano',summary:'Heroína da Guerra da Independência e um dos principais líderes revolucionários argentinos.',more:'Ambos estão associados às campanhas do Exército do Norte.',wiki:'https://pt.wikipedia.org/wiki/Manuel_Belgrano'},back:{title:'Jura da Bandeira',summary:'Recriação da cerimónia de juramento à bandeira realizada em 27 de fevereiro de 1812.',more:'O episódio está ligado a Manuel Belgrano e ao nascimento de um dos principais símbolos nacionais.',wiki:'https://pt.wikipedia.org/wiki/Bandeira_da_Argentina'}},
    'ARS:1000':{front:{title:'José de San Martín',summary:'General e estadista, figura central das independências da Argentina, Chile e Peru.',more:'San Martín liderou o Exército dos Andes.',wiki:'https://pt.wikipedia.org/wiki/Jos%C3%A9_de_San_Mart%C3%ADn'},back:{title:'Travessia dos Andes',summary:'Representação da travessia dos Andes pelo Exército dos Andes em 1817.',more:'A operação abriu caminho para a campanha libertadora do Chile.',wiki:'https://pt.wikipedia.org/wiki/Travessia_dos_Andes'}},
    'ARS:2000':{front:{title:'Ramón Carrillo e Cecilia Grierson',summary:'Dois pioneiros da medicina e da saúde pública argentinas.',more:'Grierson foi a primeira médica argentina; Carrillo teve papel decisivo na saúde pública nacional.',wiki:'https://pt.wikipedia.org/wiki/Cecilia_Grierson'},back:{title:'Instituto Dr. Carlos G. Malbrán',summary:'O reverso apresenta o Instituto Malbrán, referência argentina em microbiologia e saúde pública.',more:'A nota homenageia a saúde pública, a ciência e a medicina argentinas.',wiki:'https://pt.wikipedia.org/wiki/Instituto_Nacional_de_Enfermedades_Infecciosas'}},
    'ARS:10000':{front:{title:'María Remedios del Valle e Manuel Belgrano',summary:'Heroína da Guerra da Independência e criador da bandeira argentina.',more:'O BCRA reúne as duas figuras nesta denominação.',wiki:'https://pt.wikipedia.org/wiki/Manuel_Belgrano'},back:{title:'Jura da Bandeira · 1812',summary:'Recriação artística da cerimónia de juramento à bandeira argentina.',more:'O episódio tornou-se um marco simbólico da formação nacional.',wiki:'https://pt.wikipedia.org/wiki/Bandeira_da_Argentina'}},
    'ARS:20000':{front:{title:'Juan Bautista Alberdi',summary:'Jurista, escritor, diplomata e pensador argentino, inspirador intelectual da Constituição de 1853.',more:'A sua obra teve forte influência na organização constitucional do país.',wiki:'https://pt.wikipedia.org/wiki/Juan_Bautista_Alberdi'},back:{title:'Casa natal de Juan Bautista Alberdi',summary:'Recriação artística da casa onde Alberdi nasceu, em San Miguel de Tucumán.',more:'O reverso liga o pensador ao seu lugar de origem.',wiki:'https://pt.wikipedia.org/wiki/Juan_Bautista_Alberdi'}}
  };
  function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
  function findNoteByImage(src){try{return DB.notes.find(n=>n.front===src||n.back===src)||null}catch(_){return null}}
  function getInfo(src){const n=findNoteByImage(src);if(!n)return null;const side=n.front===src?'front':'back';const key=`${n.currency}:${Number(n.value)}`;return {note:n,side,info:INFO[key]?.[side]||window.NOTE_CONTEXT_WAVE4?.[key]?.[side]||window.NOTE_CONTEXT_WAVE3?.[key]?.[side]||window.NOTE_CONTEXT_WAVE2?.[key]?.[side]||window.NOTE_CONTEXT_GLOBAL?.get(n,side)||null}}
  function ensurePanel(){const shell=document.querySelector('.image-viewer-shell');if(!shell)return null;let panel=document.querySelector('#imageViewerContext');if(!panel){panel=document.createElement('div');panel.id='imageViewerContext';panel.className='image-viewer-context';shell.appendChild(panel)}return panel}
  function renderContext(src){const panel=ensurePanel();if(!panel)return;const hit=getInfo(src);if(!hit?.info){panel.innerHTML='<div class="note-context-muted">Descrição editorial em preparação.</div>';return}const i=hit.info;panel.innerHTML=`<div class="note-context-copy"><strong>${esc(i.title)}</strong><p>${esc(i.summary)}</p>${i.more?`<details><summary>Saber mais</summary><p>${esc(i.more)}</p></details>`:''}</div>${i.wiki?`<a class="note-context-wiki" href="${i.wiki}" target="_blank" rel="noopener noreferrer">Wikipédia ↗</a>`:''}`}
  const original=window.openImageViewer;window.openImageViewer=function(src,label='Nota'){original(src,label);renderContext(src)};
  const style=document.createElement('style');style.textContent=`.image-viewer-context{display:flex;gap:16px;align-items:flex-start;justify-content:space-between;padding:14px 18px 18px;color:#dfe8ef;background:rgba(6,15,24,.94);border-top:1px solid rgba(255,255,255,.09)}.note-context-copy{max-width:920px}.note-context-copy strong{display:block;font-size:16px;margin-bottom:5px}.note-context-copy p{margin:0;color:#b8c6d1;line-height:1.45;font-size:14px}.note-context-copy details{margin-top:7px}.note-context-copy summary{cursor:pointer;color:#e6eef4;font-size:13px}.note-context-copy details p{margin-top:6px}.note-context-wiki{flex:0 0 auto;text-decoration:none;color:#fff;border:1px solid rgba(255,255,255,.22);border-radius:999px;padding:8px 12px;font-size:13px;white-space:nowrap}.note-context-wiki:hover{background:rgba(255,255,255,.08)}.note-context-muted{color:#8395a3;font-size:13px}@media(max-width:700px){.image-viewer-context{display:block;padding:12px 14px 16px}.note-context-wiki{display:inline-block;margin-top:10px}.note-context-copy strong{font-size:15px}.note-context-copy p{font-size:13px}}`;document.head.appendChild(style);
})();