// Oceânia — países, territórios, moedas e notas locais
// Série base revista em 01-09-2026. Imagens: cópias locais importadas do Bank Note Museum.
(()=>{
 const defs=[
  {id:'AUS',name:'Austrália',flag:'🇦🇺',continent:'Oceania',region:'Australásia',currency:'AUD',capital:'Camberra',population:'≈ 27 milhões',language:'Inglês',history:[['1966–hoje','Dólar australiano (AUD)'],['1992–hoje','Famílias de notas em polímero']]},
  {id:'NZL',name:'Nova Zelândia',flag:'🇳🇿',continent:'Oceania',region:'Australásia',currency:'NZD',capital:'Wellington',population:'≈ 5,3 milhões',language:'Inglês / Māori',history:[['1967–hoje','Dólar neozelandês (NZD)'],['1999–hoje','Notas em polímero']]},
  {id:'PNG',name:'Papua-Nova Guiné',flag:'🇵🇬',continent:'Oceania',region:'Melanésia',currency:'PGK',capital:'Port Moresby',population:'≈ 10,5 milhões',language:'Inglês / Tok Pisin / Hiri Motu',history:[['1975–hoje','Kina (PGK)']]},
  {id:'FJI',name:'Fiji',flag:'🇫🇯',continent:'Oceania',region:'Melanésia',currency:'FJD',capital:'Suva',population:'≈ 930 mil',language:'Inglês / Fijiano / Hindi fijiano',history:[['1969–hoje','Dólar de Fiji (FJD)'],['2012–hoje','Flora e fauna nacionais como tema principal'],['2025/2026–hoje','Nova família de polímero']]},
  {id:'SLB',name:'Ilhas Salomão',flag:'🇸🇧',continent:'Oceania',region:'Melanésia',currency:'SBD',capital:'Honiara',population:'≈ 830 mil',language:'Inglês / Pijin',history:[['1977–hoje','Dólar das Ilhas Salomão (SBD)']]},
  {id:'VUT',name:'Vanuatu',flag:'🇻🇺',continent:'Oceania',region:'Melanésia',currency:'VUV',capital:'Port Vila',population:'≈ 340 mil',language:'Bislama / Inglês / Francês',history:[['1981–hoje','Vatu (VUV)'],['2014–hoje','Família moderna de notas; o valor de 100 vatu é atualmente moeda metálica']]},
  {id:'WSM',name:'Samoa',flag:'🇼🇸',continent:'Oceania',region:'Polinésia',currency:'WST',capital:'Apia',population:'≈ 220 mil',language:'Samoano / Inglês',history:[['1967–hoje','Tala samoano (WST)'],['2023–hoje','Família regular em polímero']]},
  {id:'TON',name:'Tonga',flag:'🇹🇴',continent:'Oceania',region:'Polinésia',currency:'TOP',capital:'Nukuʻalofa',population:'≈ 105 mil',language:'Tonganês / Inglês',history:[['1967–hoje','Paʻanga tonganês (TOP)'],['2023–hoje','Família atual do rei Tupou VI']]},
  {id:'KIR',name:'Kiribati',flag:'🇰🇮',continent:'Oceania',region:'Micronésia',currency:'AUD',capital:'Tarawa do Sul',population:'≈ 135 mil',language:'Gilbertês / Inglês',history:[['1979–hoje','Dólar australiano (AUD); Kiribati emite moedas próprias, mas não notas próprias']]},
  {id:'TUV',name:'Tuvalu',flag:'🇹🇻',continent:'Oceania',region:'Polinésia',currency:'AUD',capital:'Funafuti',population:'≈ 11 mil',language:'Tuvaluano / Inglês',history:[['1976–hoje','Dólar australiano (AUD); moedas tuvaluanas coexistem localmente']]},
  {id:'NRU',name:'Nauru',flag:'🇳🇷',continent:'Oceania',region:'Micronésia',currency:'AUD',capital:'Yaren (de facto)',population:'≈ 13 mil',language:'Nauruano / Inglês',history:[['1914–hoje','Dólar australiano (AUD) na era monetária moderna']]},
  {id:'NFK',name:'Ilha Norfolk',flag:'🇳🇫',continent:'Oceania',region:'Australásia',currency:'AUD',capital:'Kingston',population:'≈ 2,2 mil',language:'Inglês / Norfuk',history:[['século XX–hoje','Dólar australiano (AUD)']]},
  {id:'FSM',name:'Micronésia',flag:'🇫🇲',continent:'Oceania',region:'Micronésia',currency:'USD',capital:'Palikir',population:'≈ 115 mil',language:'Inglês e línguas micronésias',history:[['1944–hoje','Dólar dos Estados Unidos (USD)']]},
  {id:'MHL',name:'Ilhas Marshall',flag:'🇲🇭',continent:'Oceania',region:'Micronésia',currency:'USD',capital:'Majuro',population:'≈ 42 mil',language:'Marshallês / Inglês',history:[['1944–hoje','Dólar dos Estados Unidos (USD)']]},
  {id:'PLW',name:'Palau',flag:'🇵🇼',continent:'Oceania',region:'Micronésia',currency:'USD',capital:'Ngerulmud',population:'≈ 18 mil',language:'Palauano / Inglês',history:[['1944–hoje','Dólar dos Estados Unidos (USD)']]},
  {id:'ASM',name:'Samoa Americana',flag:'🇦🇸',continent:'Oceania',region:'Polinésia',currency:'USD',capital:'Pago Pago',population:'≈ 45 mil',language:'Samoano / Inglês',history:[['século XX–hoje','Dólar dos Estados Unidos (USD)']]},
  {id:'GUM',name:'Guam',flag:'🇬🇺',continent:'Oceania',region:'Micronésia',currency:'USD',capital:'Hagåtña',population:'≈ 170 mil',language:'Inglês / Chamorro',history:[['1944–hoje','Dólar dos Estados Unidos (USD)']]},
  {id:'MNP',name:'Ilhas Marianas do Norte',flag:'🇲🇵',continent:'Oceania',region:'Micronésia',currency:'USD',capital:'Saipan',population:'≈ 50 mil',language:'Inglês / Chamorro / Caroliniano',history:[['século XX–hoje','Dólar dos Estados Unidos (USD)']]},
  {id:'COK',name:'Ilhas Cook',flag:'🇨🇰',continent:'Oceania',region:'Polinésia',currency:'CKD',capital:'Avarua',population:'≈ 15 mil',language:'Inglês / Māori das Ilhas Cook',history:[['1967–hoje','Dólar neozelandês (NZD) como moeda principal'],['1987–hoje','Dólar das Ilhas Cook, à paridade com NZD e de circulação apenas local'],['2021–hoje','Nota local de 3 dólares em polímero']]},
  {id:'NIU',name:'Niue',flag:'🇳🇺',continent:'Oceania',region:'Polinésia',currency:'NZD',capital:'Alofi',population:'≈ 2 mil',language:'Niueano / Inglês',history:[['1967–hoje','Dólar neozelandês (NZD)']]},
  {id:'TKL',name:'Tokelau',flag:'🇹🇰',continent:'Oceania',region:'Polinésia',currency:'NZD',capital:'—',population:'≈ 2 mil',language:'Tokelauano / Inglês',history:[['1967–hoje','Dólar neozelandês (NZD)']]},
  {id:'PCN',name:'Ilhas Pitcairn',flag:'🇵🇳',continent:'Oceania',region:'Polinésia',currency:'NZD',capital:'Adamstown',population:'< 100',language:'Inglês / Pitkern',history:[['1967–hoje','Dólar neozelandês (NZD)']]},
  {id:'PYF',name:'Polinésia Francesa',flag:'🇵🇫',continent:'Oceania',region:'Polinésia',currency:'XPF',capital:'Papeete',population:'≈ 280 mil',language:'Francês / Taitiano',history:[['1945–hoje','Franco CFP (XPF)']]},
  {id:'NCL',name:'Nova Caledónia',flag:'🇳🇨',continent:'Oceania',region:'Melanésia',currency:'XPF',capital:'Nouméa',population:'≈ 270 mil',language:'Francês / línguas kanak',history:[['1945–hoje','Franco CFP (XPF)']]},
  {id:'WLF',name:'Wallis e Futuna',flag:'🇼🇫',continent:'Oceania',region:'Polinésia',currency:'XPF',capital:'Mata-Utu',population:'≈ 11 mil',language:'Francês / Wallisiano / Futuniano',history:[['1945–hoje','Franco CFP (XPF)']]}
 ];
 const currencies={
  AUD:{name:'Dólar australiano',symbol:'A$',group:'Austrália e territórios do Pacífico',source:'Reserve Bank of Australia',material:'Polímero',notes:[5,10,20,50,100],countries:['AUS','KIR','NRU','TUV','NFK'],focus:true,rate:1.78},
  NZD:{name:'Dólar neozelandês',symbol:'NZ$',group:'Nova Zelândia e territórios associados',source:'Reserve Bank of New Zealand',material:'Polímero',notes:[5,10,20,50,100],countries:['NZL','NIU','TKL','PCN'],focus:false,rate:1.96},
  PGK:{name:'Kina',symbol:'K',group:'Papua-Nova Guiné',source:'Bank of Papua New Guinea',material:'Polímero',notes:[2,5,10,20,50,100],countries:['PNG'],focus:false,rate:4.6},
  FJD:{name:'Dólar de Fiji',symbol:'FJ$',group:'Fiji',source:'Reserve Bank of Fiji',material:'Polímero',notes:[5,10,20,50,100],countries:['FJI'],focus:false,rate:2.62},
  SBD:{name:'Dólar das Ilhas Salomão',symbol:'SI$',group:'Ilhas Salomão',source:'Central Bank of Solomon Islands',material:'Papel / polímero',notes:[5,10,20,50,100],countries:['SLB'],focus:false,rate:9.8},
  VUV:{name:'Vatu',symbol:'VT',group:'Vanuatu',source:'Reserve Bank of Vanuatu',material:'Polímero / papel',notes:[200,500,1000,2000,5000,10000],countries:['VUT'],focus:false,rate:137},
  WST:{name:'Tala samoano',symbol:'WS$',group:'Samoa',source:'Central Bank of Samoa',material:'Polímero',notes:[5,10,20,50,100],countries:['WSM'],focus:false,rate:3.18},
  TOP:{name:'Paʻanga',symbol:'T$',group:'Tonga',source:'National Reserve Bank of Tonga',material:'Polímero / papel',notes:[2,5,10,20,50,100],countries:['TON'],focus:false,rate:2.75},
  XPF:{name:'Franco CFP',symbol:'₣',group:'Pacífico francês',source:"Institut d'Émission d'Outre-Mer",material:'Papel',notes:[500,1000,5000,10000],countries:['PYF','NCL','WLF'],focus:false,rate:119.3317},
  CKD:{name:'Dólar das Ilhas Cook',symbol:'$',group:'Ilhas Cook',source:'Government of the Cook Islands',material:'Polímero',notes:[3],countries:['COK'],focus:false,rate:1.96}
 };
 const iso={'036':'AUS','554':'NZL','598':'PNG','242':'FJI','090':'SLB','548':'VUT','882':'WSM','776':'TON','296':'KIR','798':'TUV','520':'NRU','574':'NFK','583':'FSM','584':'MHL','585':'PLW','016':'ASM','316':'GUM','580':'MNP','184':'COK','570':'NIU','772':'TKL','612':'PCN','258':'PYF','540':'NCL','876':'WLF'};
 const official={AUD:'https://www.rba.gov.au/banknotes/',NZD:'https://www.rbnz.govt.nz/money-and-cash/banknotes-and-coins',PGK:'https://www.bankpng.gov.pg/currency/',FJD:'https://www.rbf.gov.fj/core-functions/currency-management/',SBD:'https://www.cbsi.com.sb/currency/',VUV:'https://www.rbv.gov.vu/index.php/en/currency/current/bank-notes',WST:'https://cbs.gov.ws/currency/',TOP:'https://www.reservebank.to/currency/',XPF:'https://www.ieom.fr/',CKD:'https://cookislands.gov.ck/'};
 const museum={AUD:'https://www.banknote.ws/COLLECTION/countries/AUS/AUS/AUS-COM.htm',NZD:'https://www.banknote.ws/COLLECTION/countries/AUS/NZL/NZL-RBNZ.htm',PGK:'https://www.banknote.ws/COLLECTION/countries/AUS/PNG/PNG.htm',FJD:'https://www.banknote.ws/COLLECTION/countries/AUS/FIJ/FIJ-DOL.htm',SBD:'https://www.banknote.ws/COLLECTION/countries/AUS/SOL/SOL.htm',VUV:'https://www.banknote.ws/COLLECTION/countries/AUS/VTU/VTU-VTU.htm',WST:'https://www.banknote.ws/COLLECTION/countries/AUS/SAM/SAM.htm',TOP:'https://www.banknote.ws/COLLECTION/countries/AUS/TON/TON.htm',XPF:'https://www.banknote.ws/COLLECTION/countries/AUS/FPY/FPY.htm',CKD:'https://www.banknote.ws/COLLECTION/countries/AUS/COK/COK.htm'};
 const oldFetch=window.fetch.bind(window);
 window.fetch=async(...args)=>{const req=args[0],url=typeof req==='string'?req:req?.url||'';const r=await oldFetch(...args);
  if(url.includes('/data/countries.json')){const data=await r.clone().json();for(const c of defs){const x=data.find(v=>v.id===c.id);x?Object.assign(x,c):data.push(c)}return new Response(JSON.stringify(data),{status:r.status,statusText:r.statusText,headers:{'Content-Type':'application/json; charset=utf-8'}})}
  if(url.includes('/data/currencies.json')){const data=await r.clone().json();for(const [code,def] of Object.entries(currencies))data[code]=Object.assign({},data[code]||{},def);if(data.USD)data.USD.countries=[...new Set([...(data.USD.countries||[]),'FSM','MHL','PLW','ASM','GUM','MNP'])];return new Response(JSON.stringify(data),{status:r.status,statusText:r.statusText,headers:{'Content-Type':'application/json; charset=utf-8'}})}
  if(url.includes('/data/iso-map.json')){const data=await r.clone().json();Object.assign(data,iso);return new Response(JSON.stringify(data),{status:r.status,statusText:r.statusText,headers:{'Content-Type':'application/json; charset=utf-8'}})}
  if(url.includes('/data/notes.json')){const data=await r.clone().json();for(const [code,def] of Object.entries(currencies))for(const value of def.notes){let n=data.find(x=>x.currency===code&&Number(x.value)===Number(value));if(!n){n={currency:code,value};data.push(n)}Object.assign(n,{status:'circulating',statusLabel:'Em circulação',source:def.source,material:def.material,front:`/assets/notes/banknotews/${code.toLowerCase()}/${value}-front.jpg`,back:`/assets/notes/banknotews/${code.toLowerCase()}/${value}-back.jpg`,imageStatus:'local-reference',imageSource:'Bank Note Museum · cópia local',imageSourceUrl:museum[code],officialUrl:official[code],officialLabel:`Ver ${code} na fonte oficial`})}return new Response(JSON.stringify(data),{status:r.status,statusText:r.statusText,headers:{'Content-Type':'application/json; charset=utf-8'}})}
  return r;
 };
})();
